# Merge the translation tables and write js/lang/<code>.js. Run: python3 tools/lang/build.py
import importlib.util, json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'js', 'lang')
CODES = ['pt', 'es', 'fr', 'de']
rows, seen, problems = [], {}, 0
for name in sorted(f for f in os.listdir(HERE) if f.startswith('p') and f.endswith('.py')):
    spec = importlib.util.spec_from_file_location(name[:-3], os.path.join(HERE, name))
    mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
    for r in mod.ROWS:
        if len(r) != 5: print('bad row', name, r[:1]); problems += 1; continue
        if r[0] in seen and seen[r[0]] != r: print('different duplicate:', r[0])
        seen[r[0]] = r
        rows.append(r)
os.makedirs(OUT, exist_ok=True)
for i, code in enumerate(CODES):
    d = {r[0]: r[i + 1] for r in seen.values()}
    # placeholders must survive translation
    import re
    for k, v in d.items():
        if sorted(re.findall(r'\{\w+\}', k)) != sorted(re.findall(r'\{\w+\}', v)) or k.count('#') != len(re.findall(r'#\d?', v)):
            print(f'[{code}] placeholder mismatch: {k!r} -> {v!r}'); problems += 1
    with open(os.path.join(OUT, code + '.js'), 'w', encoding='utf-8') as f:
        f.write("'use strict';\n/* Generated by tools/lang/build.py from the tables in tools/lang. Edit those, not this. */\n")
        f.write(f"L10N.add('{code}', " + json.dumps(d, ensure_ascii=False, indent=0) + ");\n")
# Chinese lives in its own tables (zh_*.py), keyed by the same English text
zh = {}
for name in sorted(f for f in os.listdir(HERE) if f.startswith('zh_') and f.endswith('.py')):
    spec = importlib.util.spec_from_file_location(name[:-3], os.path.join(HERE, name))
    mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
    for k, v in mod.ZH: zh[k] = v
for k in seen:
    if k not in zh: print('[zh] missing:', repr(k)); problems += 1
for k, v in zh.items():
    if k not in seen: print('[zh] not an English key:', repr(k)); problems += 1
    elif sorted(re.findall(r'\{\w+\}', k)) != sorted(re.findall(r'\{\w+\}', v)) or k.count('#') != len(re.findall(r'#\d?', v)):
        print(f'[zh] placeholder mismatch: {k!r} -> {v!r}'); problems += 1
with open(os.path.join(OUT, 'zh.js'), 'w', encoding='utf-8') as f:
    f.write("'use strict';\n/* Generated by tools/lang/build.py from the tables in tools/lang. Edit those, not this. */\n")
    f.write("L10N.add('zh', " + json.dumps(zh, ensure_ascii=False, indent=0) + ");\n")
print(len(seen), 'strings,', problems, 'problems')
sys.exit(1 if problems else 0)
