'use strict';
/* Ant species. Ten are playable; the red wood ant only appears as a rival. */

const ANT_SPECIES = {
  garden: {
    name: 'Black garden ant', latin: 'Lasius niger', playable: true,
    pal: { g: ['#2a1e19', '#7a6252', '#0a0605'], t: ['#2e211b', '#806856', '#0c0806'], h: ['#2b1f1a', '#7d6553', '#0a0605'], leg: '#1c120e', ant: '#24170f' },
    shape: { size: 1, head: 1, gaster: 1, legs: 1, nodes: 1, mand: 'normal', spines: false, hairs: false, slim: 1 },
    stats: { speed: 1, hp: 1, dmg: 1 }, costW: 8, costS: 20,
    ability: { id: 'share', name: 'Share food', cd: 10, desc: 'Heal yourself and every sister nearby.' },
    perk: 'Aphid herders: honeydew is worth 3 food instead of 2.',
    nest: 'crater', trail: [255, 214, 120],
    blurb: 'A worker that finds food lays a scent trail on the way home, and her sisters follow it. When two meet they tap antennae to share news, and sometimes food.',
  },
  leafcutter: {
    name: 'Leafcutter ant', latin: 'Atta cephalotes', playable: true,
    pal: { g: ['#6e3416', '#c47a44', '#240c04'], t: ['#87431e', '#e09858', '#2e1206'], h: ['#8a451f', '#e49c5c', '#2e1206'], leg: '#5a2a10', ant: '#4a200a' },
    shape: { size: 1.05, head: 1.22, gaster: 0.72, legs: 1.2, nodes: 2, mand: 'leaf', spines: true, hairs: false, slim: 1 },
    stats: { speed: 0.95, hp: 1.1, dmg: 1.1 }, costW: 9, costS: 22,
    ability: { id: 'cut', name: 'Cut leaf', cd: 1.2, desc: 'Snip a leaf fragment from the plants around you.' },
    perk: 'Fungus farmers: carried leaves feed the fungus garden, which turns them into food.',
    nest: 'bare', trail: [255, 170, 90],
    blurb: 'Leafcutters do not eat the leaves they carry. They chew them into a mulch that feeds a fungus garden, and the fungus feeds the colony.',
  },
  fire: {
    name: 'Red fire ant', latin: 'Solenopsis invicta', playable: true,
    pal: { g: ['#3c1c12', '#8e5444', '#140604'], t: ['#a8481c', '#f2a062', '#3c1206'], h: ['#a4441a', '#ee985a', '#3a1106'], leg: '#6a2a10', ant: '#5a200a' },
    shape: { size: 0.86, head: 1, gaster: 1, legs: 0.95, nodes: 2, mand: 'normal', spines: false, hairs: false, slim: 1 },
    stats: { speed: 1.05, hp: 0.75, dmg: 0.8 }, costW: 5, costS: 14, venom: true, swims: true,
    ability: { id: 'venom', name: 'Venom burst', cd: 8, desc: 'Sting every enemy around you. The venom keeps burning.' },
    perk: 'Cheap, venomous workers. You can paddle across water.',
    nest: 'dome', trail: [255, 120, 80],
    blurb: 'Fire ants sting with a venom that burns. When floods come they link legs and float together as a living raft.',
  },
  trapjaw: {
    name: 'Trap-jaw ant', latin: 'Odontomachus bauri', playable: true,
    pal: { g: ['#5a2c14', '#c27c4a', '#1a0804'], t: ['#5e2e16', '#c8824e', '#1c0904'], h: ['#5c2d15', '#c6804c', '#1a0804'], leg: '#3a1a0a', ant: '#2e1408' },
    shape: { size: 1.15, head: 1.12, gaster: 0.95, legs: 1.2, nodes: 1, mand: 'trap', spines: false, hairs: false, slim: 0.9 },
    stats: { speed: 1.05, hp: 1.05, dmg: 1.7 }, costW: 10, costS: 24,
    ability: { id: 'leap', name: 'Jaw leap', cd: 4, desc: 'Snap your jaws on the ground and fly forward, hitting anything in the way.' },
    perk: 'Spring-loaded jaws hit very hard.',
    nest: 'litter', trail: [240, 190, 110],
    blurb: 'Its jaws lock open and snap shut in a fraction of a millisecond, one of the fastest movements in the animal world. It can even snap them against the ground to fling itself away.',
  },
  bullet: {
    name: 'Bullet ant', latin: 'Paraponera clavata', playable: true,
    pal: { g: ['#26130c', '#6e4636', '#080302'], t: ['#2c160e', '#74493a', '#0a0402'], h: ['#2a150d', '#704737', '#080302'], leg: '#1a0c08', ant: '#140804' },
    shape: { size: 1.5, head: 1.05, gaster: 1.08, legs: 1.05, nodes: 1, mand: 'normal', spines: false, hairs: true, slim: 1 },
    stats: { speed: 0.86, hp: 2.2, dmg: 2 }, costW: 14, costS: 30,
    ability: { id: 'sting', name: 'Bullet sting', cd: 6, desc: 'A crushing sting that stuns your target.' },
    perk: 'Huge and tough, but each new sister costs a lot of food.',
    nest: 'roots', trail: [230, 160, 130],
    blurb: 'One of the largest ants in the world. Its sting is often rated the most painful of any insect.',
  },
  weaver: {
    name: 'Weaver ant', latin: 'Oecophylla smaragdina', playable: true,
    pal: { g: ['#7a8a2a', '#dce474', '#2a3008'], t: ['#c4681c', '#ffb464', '#4a1e04'], h: ['#c2661c', '#ffb262', '#4a1e04'], leg: '#a05418', ant: '#8a4410' },
    shape: { size: 1.1, head: 1, gaster: 0.9, legs: 1.35, nodes: 1, mand: 'normal', spines: false, hairs: false, slim: 0.82 },
    stats: { speed: 1.18, hp: 0.95, dmg: 1.05 }, costW: 9, costS: 22,
    ability: { id: 'weave', name: 'Weave outpost', cd: 2, desc: 'Spend 15 food to build a leaf shelter where sisters drop food and heal (up to 3).' },
    perk: 'Fast and long-legged. Builds outposts far from home.',
    nest: 'leafball', trail: [200, 240, 120],
    blurb: 'Weaver ants pull leaves together and glue them with silk spun by their own larvae, which workers hold in their jaws like living glue guns.',
  },
  army: {
    name: 'Army ant', latin: 'Eciton burchellii', playable: true,
    pal: { g: ['#7a4418', '#d08a48', '#2a1206'], t: ['#8a4c1c', '#dc9450', '#2e1406'], h: ['#9a5420', '#e8a058', '#341606'], leg: '#5a2c10', ant: '#3a1a08' },
    shape: { size: 1.05, head: 1.05, gaster: 0.85, legs: 1.3, nodes: 2, mand: 'hook', spines: false, hairs: false, slim: 0.85, blind: true },
    stats: { speed: 1.15, hp: 0.9, dmg: 1.2 }, costW: 7, costS: 18,
    ability: { id: 'swarm', name: 'Swarm raid', cd: 16, desc: 'Every sister nearby surges at the closest prey and bites 30% harder for 8 seconds.' },
    perk: 'Raiders: soldiers have huge hooked jaws, and sisters hunt in packs.',
    nest: 'bivouac', trail: [255, 160, 70],
    blurb: 'Army ants are nearly blind and never build a nest. They camp in a living ball made of their own linked bodies, then pour out in raids of hundreds of thousands.',
  },
  honeypot: {
    name: 'Honeypot ant', latin: 'Myrmecocystus mexicanus', playable: true,
    pal: { g: ['#b07a2a', '#f4c870', '#5a3a0a'], t: ['#a8743a', '#e8b878', '#4a2a10'], h: ['#9a6a34', '#e0ae70', '#40240c'], leg: '#6a4420', ant: '#5a3818' },
    shape: { size: 1, head: 1, gaster: 1.15, legs: 1.15, nodes: 1, mand: 'normal', spines: false, hairs: false, slim: 0.9 },
    stats: { speed: 1.05, hp: 0.95, dmg: 0.9 }, costW: 8, costS: 20,
    ability: { id: 'lure', name: 'Honey lure', cd: 18, desc: 'Drop a sweet bead that draws nearby insects in for 12 seconds, right into your sisters’ jaws.' },
    perk: 'Living larders: the granary holds 80 more food, and honeydew is worth 3.',
    nest: 'turret', trail: [255, 200, 90],
    blurb: 'Some workers become living storage jars, called repletes. They hang from the nest ceiling with abdomens swollen with honey, feeding sisters in lean times.',
  },
  carpenter: {
    name: 'Carpenter ant', latin: 'Camponotus herculeanus', playable: true,
    pal: { g: ['#1a1412', '#5a4a44', '#050302'], t: ['#5a2018', '#a85a48', '#200806'], h: ['#1e1614', '#605048', '#060403'], leg: '#3a1a14', ant: '#140c0a' },
    shape: { size: 1.35, head: 1.15, gaster: 1.05, legs: 1.1, nodes: 1, mand: 'normal', spines: false, hairs: true, slim: 1 },
    stats: { speed: 0.95, hp: 1.6, dmg: 1.4 }, costW: 11, costS: 26,
    ability: { id: 'gnaw', name: 'Gnaw through', cd: 14, desc: 'For 6 seconds you chew straight through logs, stumps and stones.' },
    perk: 'Big and strong. Does not eat wood, but tunnels through it.',
    nest: 'stump', trail: [220, 170, 140],
    blurb: 'Carpenter ants carve galleries in damp, rotting wood. They do not eat it: the sawdust they push out piles up below the nest entrance.',
  },
  harvester: {
    name: 'Harvester ant', latin: 'Pogonomyrmex barbatus', playable: true,
    pal: { g: ['#7a2a14', '#c86a44', '#2a0c04'], t: ['#8a3018', '#d8764c', '#2e0e04'], h: ['#8e3218', '#dc7a50', '#300e04'], leg: '#5a1e0c', ant: '#4a1806' },
    shape: { size: 1.12, head: 1.18, gaster: 0.95, legs: 1.05, nodes: 2, mand: 'normal', spines: true, hairs: false, slim: 1, beard: true },
    stats: { speed: 0.95, hp: 1.15, dmg: 1.2 }, costW: 9, costS: 22, venom: true,
    ability: { id: 'potent', name: 'Potent sting', cd: 9, desc: 'A sting with one of the strongest venoms of any insect: heavy poison on one target.' },
    perk: 'Seed gatherers: seeds and sunflower seeds are worth double.',
    nest: 'disc', trail: [255, 140, 90],
    blurb: 'Harvester ants clear a bare disc around their nest and store seeds in underground granaries. The bristly "beard" under the head carries sand and seeds.',
  },
  wood: {
    name: 'Red wood ant', latin: 'Formica rufa', playable: false,
    pal: { g: ['#2d1813', '#7c4a3a', '#0b0503'], t: ['#a83c17', '#f6a066', '#3c1106'], h: ['#933416', '#ee8e58', '#330e05'], leg: '#4d1b0c', ant: '#5c200e' },
    shape: { size: 1.05, head: 1, gaster: 1, legs: 1.05, nodes: 1, mand: 'normal', spines: false, hairs: false, slim: 1 },
    stats: { speed: 1, hp: 1.1, dmg: 1.1 }, costW: 8, costS: 20,
    ability: null, perk: '', nest: 'thatch', trail: [255, 110, 150],
    blurb: 'Builds big domed mounds out of pine needles and defends them hard. Instead of stinging, it sprays formic acid.',
  },
};

const PLAYABLE = Object.keys(ANT_SPECIES).filter((k) => ANT_SPECIES[k].playable);
const RIVALS = ['wood', 'fire', 'leafcutter', 'trapjaw', 'bullet', 'weaver', 'garden', 'wood', 'army', 'honeypot', 'carpenter', 'harvester'];
