// Packs every recording in assets/audio/ into assets/audio/embedded.js (base64), so the game can
// play them even when index.html is opened straight from disk (file://), where fetch() is blocked.
// Run after adding or changing a file:   node tools/embed-audio.js
const fs = require('fs'), path = require('path');
const dir = path.join(__dirname, '..', 'assets', 'audio');
const files = fs.readdirSync(dir).filter((f) => /\.(mp3|ogg|wav|m4a)$/i.test(f)).sort();
const lines = files.map((f) => `  'assets/audio/${f}': '${fs.readFileSync(path.join(dir, f)).toString('base64')}'`);
fs.writeFileSync(path.join(dir, 'embedded.js'),
  '// GENERATED by tools/embed-audio.js from the files in this folder. Do not edit by hand.\n' +
  'var AQ = (typeof AQ !== \'undefined\') ? AQ : {};\nAQ.data = AQ.data || {};\n' +
  'AQ.data.audioEmbedded = {\n' + lines.join(',\n') + '\n};\n');
console.log(`embedded ${files.length} files`);
