// Packs every sprite PNG listed in assets/manifest.js into assets/sprites-embedded.js (base64).
// The game only uses it when index.html is opened straight from disk (file://): browsers treat
// file:// images as "tainted", which blocks saving tank photos. Over http the PNGs load normally.
// tools/gen-placeholders.js runs this automatically; after replacing art by hand, run:
//   node tools/embed-sprites.js
const fs = require('fs'), path = require('path'), vm = require('vm');
const ROOT = path.join(__dirname, '..');
function run() {
  const ctx = {}; vm.createContext(ctx);
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'assets/manifest.js'), 'utf8'), ctx);
  const files = [...new Set(Object.values(ctx.AQ.manifest.sprites).map((e) => e.file))].sort();
  const lines = [];
  for (const f of files) {
    const p = path.join(ROOT, 'assets', f);
    if (fs.existsSync(p)) lines.push(`  '${f}': '${fs.readFileSync(p).toString('base64')}'`);
  }
  fs.writeFileSync(path.join(ROOT, 'assets/sprites-embedded.js'),
    '// GENERATED by tools/embed-sprites.js from assets/sprites/. Do not edit by hand.\n' +
    'var AQ = (typeof AQ !== \'undefined\') ? AQ : {};\nAQ.spriteData = {\n' + lines.join(',\n') + '\n};\n');
  return lines.length;
}
if (require.main === module) console.log(`embedded ${run()} sprites`);
module.exports = run;
