# UsForge's translations, all in one table: English, then Português, Español, Français, Deutsch, 中文.
# Run `python3 scripts/langs.py` after editing to rebuild lang/pt.js, lang/es.js, lang/fr.js, lang/de.js and lang/zh.js.
# To translate something new: add a row with the exact English text as it appears on the page (no extra spaces).
# PATTERNS cover sentences with a name or number in them; {t:$1} means "translate that part too".
import json
from pathlib import Path

CODES = ['pt', 'es', 'fr', 'de', 'zh']

ROWS = [
  # ---------- menu, banners, footer ----------
  ('Games', 'Jogos', 'Juegos', 'Jeux', 'Spiele', '游戏'),
  ('Share your game', 'Partilha o teu jogo', 'Comparte tu juego', 'Partage ton jeu', 'Teile dein Spiel', '分享你的游戏'),
  ('Upload', 'Carregar', 'Subir', 'Publier', 'Hochladen', '上传'),
  ('Credits', 'Créditos', 'Créditos', 'Crédits', 'Credits', '制作人员'),
  ('Support', 'Apoiar', 'Apoyar', 'Soutenir', 'Unterstützen', '支持'),
  ('You', 'Tu', 'Tú', 'Toi', 'Du', '我的'),
  ('Settings', 'Definições', 'Ajustes', 'Réglages', 'Einstellungen', '设置'),
  ('Notifications', 'Notificações', 'Notificaciones', 'Notifications', 'Benachrichtigungen', '通知'),
  ('Get the app', 'Obter a app', 'Obtener la app', 'Obtenir l’app', 'App holen', '获取应用'),
  ('Language', 'Idioma', 'Idioma', 'Langue', 'Sprache', '语言'),
  ('Languages', 'Idiomas', 'Idiomas', 'Langues', 'Sprachen', '语言'),
  ('Some games are only in one language. Translating the site doesn’t change the words inside a game.',
   'Alguns jogos só existem numa língua. Traduzir o site não muda as palavras dentro de um jogo.',
   'Algunos juegos solo están en un idioma. Traducir el sitio no cambia las palabras dentro de un juego.',
   'Certains jeux n’existent que dans une seule langue. Traduire le site ne change pas les mots dans un jeu.',
   'Manche Spiele gibt es nur in einer Sprache. Die Übersetzung der Seite ändert nichts an den Wörtern im Spiel.',
   '有些游戏只有一种语言。翻译网站不会改变游戏里面的文字。'),
  ('Auto', 'Auto', 'Auto', 'Auto', 'Auto', '自动'),
  ('Light', 'Claro', 'Claro', 'Clair', 'Hell', '浅色'),
  ('Dark', 'Escuro', 'Oscuro', 'Sombre', 'Dunkel', '深色'),
  ('Announcement', 'Anúncio', 'Anuncio', 'Annonce', 'Ankündigung', '公告'),
  ('We need more members!', 'Precisamos de mais membros!', '¡Necesitamos más miembros!', 'On cherche plus de membres !', 'Wir brauchen mehr Mitglieder!', '我们需要更多成员！'),
  ('Make games with AI? Join UsForge and share them with everyone.', 'Fazes jogos com IA? Junta-te ao UsForge e partilha-os com todos.', '¿Haces juegos con IA? Únete a UsForge y compártelos con todos.', 'Tu crées des jeux avec l’IA ? Rejoins UsForge et partage-les avec tout le monde.', 'Du machst Spiele mit KI? Komm zu UsForge und teile sie mit allen.', '用 AI 做游戏？加入 UsForge，和大家分享吧。'),
  ('How to join →', 'Como entrar →', 'Cómo unirse →', 'Comment rejoindre →', 'So machst du mit →', '如何加入 →'),
  ('Close this message', 'Fechar esta mensagem', 'Cerrar este mensaje', 'Fermer ce message', 'Diese Nachricht schließen', '关闭此消息'),
  ('Enjoying UsForge?', 'Estás a gostar do UsForge?', '¿Te gusta UsForge?', 'Tu aimes UsForge ?', 'Gefällt dir UsForge?', '喜欢 UsForge 吗？'),
  ('It’s free with no ads. A small tip helps us keep it running.', 'É grátis e sem anúncios. Uma pequena gorjeta ajuda-nos a mantê-lo a funcionar.', 'Es gratis y sin anuncios. Una pequeña propina nos ayuda a mantenerlo.', 'C’est gratuit et sans pub. Un petit pourboire nous aide à le faire tourner.', 'Es ist kostenlos und ohne Werbung. Ein kleines Trinkgeld hilft uns, es am Laufen zu halten.', '免费且无广告。一点小费就能帮我们继续运营。'),
  ('Support us →', 'Apoia-nos →', 'Apóyanos →', 'Soutiens-nous →', 'Unterstütze uns →', '支持我们 →'),
  ('Scroll to top', 'Ir para o topo', 'Ir arriba', 'Remonter en haut', 'Nach oben', '回到顶部'),
  ('Scroll to bottom', 'Ir para o fim', 'Ir abajo', 'Descendre en bas', 'Nach unten', '到底部'),
  ('UsForge · by Lazy Studios', 'UsForge · pela Lazy Studios', 'UsForge · por Lazy Studios', 'UsForge · par Lazy Studios', 'UsForge · von Lazy Studios', 'UsForge · Lazy Studios 出品'),
  ('UsForge · Site by Taurus', 'UsForge · Site do Taurus', 'UsForge · Sitio de Taurus', 'UsForge · Site par Taurus', 'UsForge · Seite von Taurus', 'UsForge · 网站由 Taurus 制作'),
  ('Site by Taurus · Lazy Studios', 'Site do Taurus · Lazy Studios', 'Sitio de Taurus · Lazy Studios', 'Site par Taurus · Lazy Studios', 'Seite von Taurus · Lazy Studios', '网站由 Taurus 制作 · Lazy Studios'),
  ('Support Lazy Studios', 'Apoiar a Lazy Studios', 'Apoyar a Lazy Studios', 'Soutenir Lazy Studios', 'Lazy Studios unterstützen', '支持 Lazy Studios'),
  ('Share your game →', 'Partilha o teu jogo →', 'Comparte tu juego →', 'Partage ton jeu →', 'Teile dein Spiel →', '分享你的游戏 →'),
  ('Back to the games →', 'Voltar aos jogos →', 'Volver a los juegos →', 'Retour aux jeux →', 'Zurück zu den Spielen →', '返回游戏 →'),
  ('Back to the games', 'Voltar aos jogos', 'Volver a los juegos', 'Retour aux jeux', 'Zurück zu den Spielen', '返回游戏'),
  ('See what everyone’s playing', 'Vê o que todos estão a jogar', 'Mira lo que todos están jugando', 'Vois à quoi tout le monde joue', 'Sieh, was alle gerade spielen', '看看大家在玩什么'),
  ('Right now on UsForge', 'Agora no UsForge', 'Ahora en UsForge', 'En ce moment sur UsForge', 'Gerade auf UsForge', 'UsForge 此刻'),
  ('Nobody’s in a game right now.', 'Ninguém está a jogar agora.', 'Nadie está jugando ahora.', 'Personne ne joue en ce moment.', 'Gerade spielt niemand.', '现在没有人在玩游戏。'),
  ('Updates every 30 seconds · no names, just numbers', 'Atualiza a cada 30 segundos · sem nomes, só números', 'Se actualiza cada 30 segundos · sin nombres, solo números', 'Mis à jour toutes les 30 secondes · pas de noms, juste des chiffres', 'Aktualisiert alle 30 Sekunden · keine Namen, nur Zahlen', '每 30 秒更新 · 没有名字，只有数字'),
  ('Since your last visit', 'Desde a tua última visita', 'Desde tu última visita', 'Depuis ta dernière visite', 'Seit deinem letzten Besuch', '自你上次访问以来'),
  ('Nothing new right now. New games, updates to your favorites and leaderboard news show up here.', 'Nada de novo por agora. Novos jogos, atualizações dos teus favoritos e novidades das classificações aparecem aqui.', 'Nada nuevo por ahora. Aquí aparecen juegos nuevos, novedades de tus favoritos y de las clasificaciones.', 'Rien de neuf pour l’instant. Les nouveaux jeux, les mises à jour de tes favoris et les nouvelles des classements apparaissent ici.', 'Gerade nichts Neues. Neue Spiele, Updates deiner Favoriten und Bestenlisten-News erscheinen hier.', '现在没有新消息。新游戏、收藏的更新和排行榜消息会显示在这里。'),
  ('New game:', 'Novo jogo:', 'Juego nuevo:', 'Nouveau jeu :', 'Neues Spiel:', '新游戏：'),
  ('updated:', 'atualizado:', 'actualizado:', 'mis à jour :', 'aktualisiert:', '已更新：'),
  ('Your favorite', 'O teu favorito', 'Tu favorito', 'Ton favori', 'Dein Favorit', '你收藏的'),
  ('was updated', 'foi atualizado', 'se actualizó', 'a été mis à jour', 'wurde aktualisiert', '已更新'),
  # ---------- home page ----------
  ('Welcome to UsForge', 'Bem-vindo ao UsForge', 'Bienvenido a UsForge', 'Bienvenue sur UsForge', 'Willkommen bei UsForge', '欢迎来到 UsForge'),
  ('by Lazy Studios', 'pela Lazy Studios', 'por Lazy Studios', 'par Lazy Studios', 'von Lazy Studios', 'Lazy Studios 出品'),
  ('Continue', 'Continuar', 'Continuar', 'Continuer', 'Weiter', '继续'),
  ('What is UsForge?', 'O que é o UsForge?', '¿Qué es UsForge?', 'C’est quoi UsForge ?', 'Was ist UsForge?', 'UsForge 是什么？'),
  ('A hub for AI games', 'Um ponto de encontro para jogos feitos com IA', 'Un lugar para juegos hechos con IA', 'Un repaire de jeux faits avec l’IA', 'Ein Zuhause für KI-Spiele', 'AI 游戏的聚集地'),
  ('Started by four friends at Lazy Studios, now a growing community, and every game here is built with the help of AI.', 'Começou com quatro amigos na Lazy Studios, agora é uma comunidade a crescer, e todos os jogos aqui são feitos com a ajuda de IA.', 'Empezó con cuatro amigos en Lazy Studios, ahora es una comunidad que crece, y cada juego de aquí está hecho con ayuda de la IA.', 'Lancé par quatre amis chez Lazy Studios, c’est maintenant une communauté qui grandit, et chaque jeu ici est fait avec l’aide de l’IA.', 'Gestartet von vier Freunden bei Lazy Studios, jetzt eine wachsende Community, und jedes Spiel hier ist mit Hilfe von KI gemacht.', '由 Lazy Studios 的四个朋友创立，现在是一个不断壮大的社区，这里的每个游戏都是在 AI 的帮助下制作的。'),
  ('Free to play, right in your browser', 'Grátis, diretamente no teu navegador', 'Gratis, directamente en tu navegador', 'Gratuit, directement dans ton navigateur', 'Kostenlos, direkt im Browser', '免费，直接在浏览器里玩'),
  ('New games from the crew all the time', 'Jogos novos da equipa a toda a hora', 'Juegos nuevos del equipo todo el tiempo', 'De nouveaux jeux de l’équipe tout le temps', 'Ständig neue Spiele vom Team', '团队不断推出新游戏'),
  ('No ads, no sign-ups', 'Sem anúncios, sem registos', 'Sin anuncios, sin registros', 'Pas de pub, pas d’inscription', 'Keine Werbung, keine Anmeldung', '无广告，无需注册'),
  ('Let’s play', 'Vamos jogar', 'A jugar', 'On joue', 'Los geht’s', '开玩吧'),
  ('Started by Taurus, Henrique, Alex and Igor.', 'Começado pelo Taurus, Henrique, Alex e Igor.', 'Creado por Taurus, Henrique, Alex e Igor.', 'Lancé par Taurus, Henrique, Alex et Igor.', 'Gestartet von Taurus, Henrique, Alex und Igor.', '由 Taurus、Henrique、Alex 和 Igor 创立。'),
  ('Now a community.', 'Agora uma comunidade.', 'Ahora una comunidad.', 'Maintenant une communauté.', 'Jetzt eine Community.', '如今是一个社区。'),
  ('Makers', 'Criadores', 'Creadores', 'Créateurs', 'Macher', '创作者'),
  ('Plays', 'Jogadas', 'Partidas', 'Parties', 'Spielrunden', '游玩次数'),
  ('Stokes', 'Atiçadas', 'Avivadas', 'Flammes', 'Anfacher', '添柴'),
  ('In development', 'Em desenvolvimento', 'En desarrollo', 'En développement', 'In Entwicklung', '开发中'),
  ('Founder picks', 'Escolhas dos fundadores', 'Elegidos por los fundadores', 'Choix des fondateurs', 'Tipps der Gründer', '创始人推荐'),
  ('starred by Lazy Studios', 'com estrela da Lazy Studios', 'destacados por Lazy Studios', 'mis en avant par Lazy Studios', 'von Lazy Studios markiert', 'Lazy Studios 星标'),
  ('Your favorites', 'Os teus favoritos', 'Tus favoritos', 'Tes favoris', 'Deine Favoriten', '你的收藏'),
  ('see all on your page →', 'vê todos na tua página →', 'ver todos en tu página →', 'tout voir sur ta page →', 'alle auf deiner Seite →', '在你的页面查看全部 →'),
  ('Jump back in', 'Volta a jogar', 'Vuelve a jugar', 'Reprends', 'Weiterspielen', '继续游玩'),
  ('games you played lately', 'jogos que jogaste há pouco', 'juegos que jugaste hace poco', 'jeux auxquels tu as joué récemment', 'Spiele, die du zuletzt gespielt hast', '你最近玩过的游戏'),
  ('The library', 'A biblioteca', 'La biblioteca', 'La bibliothèque', 'Die Bibliothek', '游戏库'),
  ('Search games, makers, genres  ( / )', 'Procurar jogos, criadores, géneros  ( / )', 'Buscar juegos, creadores, géneros  ( / )', 'Chercher des jeux, créateurs, genres  ( / )', 'Spiele, Macher, Genres suchen  ( / )', '搜索游戏、创作者、类型  ( / )'),
  ('Search games, makers and genres', 'Procurar jogos, criadores e géneros', 'Buscar juegos, creadores y géneros', 'Chercher des jeux, créateurs et genres', 'Spiele, Macher und Genres suchen', '搜索游戏、创作者和类型'),
  ('Sort', 'Ordenar', 'Ordenar', 'Trier', 'Sortieren', '排序'),
  ('Newest', 'Mais recentes', 'Más nuevos', 'Plus récents', 'Neueste', '最新'),
  ('Most played', 'Mais jogados', 'Más jugados', 'Les plus joués', 'Meistgespielt', '最多游玩'),
  ('Most stoked', 'Mais atiçados', 'Más avivados', 'Les plus attisés', 'Am meisten angefacht', '最多添柴'),
  ('A–Z', 'A–Z', 'A–Z', 'A–Z', 'A–Z', 'A–Z'),
  ('Maker', 'Criador', 'Creador', 'Créateur', 'Macher', '创作者'),
  ('Genre', 'Género', 'Género', 'Genre', 'Genre', '类型'),
  ('Surprise me', 'Surpreende-me', 'Sorpréndeme', 'Surprends-moi', 'Überrasch mich', '给我惊喜'),
  ('Still being made at Lazy Studios: try the early builds, and keep an eye on what’s coming.', 'Ainda a serem feitos na Lazy Studios: experimenta as versões iniciais e fica atento ao que aí vem.', 'Aún en preparación en Lazy Studios: prueba las versiones tempranas y atento a lo que viene.', 'Encore en fabrication chez Lazy Studios : essaie les premières versions et garde un œil sur ce qui arrive.', 'Noch in Arbeit bei Lazy Studios: Probier die frühen Versionen und behalte im Blick, was kommt.', 'Lazy Studios 仍在制作中：试玩早期版本，留意即将推出的内容。'),
  ('Play now', 'Jogar agora', 'Jugar ahora', 'Jouer maintenant', 'Jetzt spielen', '立即开玩'),
  ('Details', 'Detalhes', 'Detalles', 'Détails', 'Details', '详情'),
  ('Everyone', 'Todos', 'Todos', 'Tout le monde', 'Alle', '所有人'),
  ('All', 'Todos', 'Todos', 'Tous', 'Alle', '全部'),
  ('Updated', 'Atualizado', 'Actualizado', 'Mis à jour', 'Aktualisiert', '已更新'),
  ('Early build', 'Versão inicial', 'Versión temprana', 'Première version', 'Frühe Version', '早期版本'),
  ('Next up:', 'A seguir:', 'Lo próximo:', 'Ensuite :', 'Als Nächstes:', '下一步：'),
  ('Game of the day', 'Jogo do dia', 'Juego del día', 'Jeu du jour', 'Spiel des Tages', '今日游戏'),
  # ---------- genres ----------
  ('How it plays', 'Como se joga', 'Cómo se juega', 'Le gameplay', 'Spielweise', '玩法'),
  ('Cards, words & friends', 'Cartas, palavras e amigos', 'Cartas, palabras y amigos', 'Cartes, mots et amis', 'Karten, Wörter & Freunde', '卡牌、文字与朋友'),
  ('Mood & setting', 'Ambiente e cenário', 'Ambiente y escenario', 'Ambiance et univers', 'Stimmung & Setting', '氛围与背景'),
  ('Action', 'Ação', 'Acción', 'Action', 'Action', '动作'),
  ('Adventure', 'Aventura', 'Aventura', 'Aventure', 'Abenteuer', '冒险'),
  ('Arcade', 'Arcada', 'Arcade', 'Arcade', 'Arcade', '街机'),
  ('Boss rush', 'Só chefes', 'Jefes seguidos', 'Boss rush', 'Boss-Rush', '连战首领'),
  ('Casual', 'Casual', 'Casual', 'Détente', 'Gelegenheitsspiel', '休闲'),
  ('Crafting', 'Construção de objetos', 'Fabricación', 'Fabrication', 'Crafting', '制作'),
  ('Endless runner', 'Corrida sem fim', 'Carrera infinita', 'Course sans fin', 'Endlos-Läufer', '无尽跑酷'),
  ('Exploration', 'Exploração', 'Exploración', 'Exploration', 'Erkundung', '探索'),
  ('Fighting', 'Luta', 'Lucha', 'Combat', 'Kampf', '格斗'),
  ('Idle', 'Idle', 'Idle', 'Idle', 'Idle', '放置'),
  ('Management', 'Gestão', 'Gestión', 'Gestion', 'Management', '经营'),
  ('Open world', 'Mundo aberto', 'Mundo abierto', 'Monde ouvert', 'Offene Welt', '开放世界'),
  ('Physics', 'Física', 'Física', 'Physique', 'Physik', '物理'),
  ('Platformer', 'Plataformas', 'Plataformas', 'Plateforme', 'Jump ’n’ Run', '平台跳跃'),
  ('Puzzle', 'Quebra-cabeças', 'Puzle', 'Puzzle', 'Rätsel', '解谜'),
  ('Racing', 'Corridas', 'Carreras', 'Course', 'Rennspiel', '竞速'),
  ('Rhythm', 'Ritmo', 'Ritmo', 'Rythme', 'Rhythmus', '节奏'),
  ('Roguelike', 'Roguelike', 'Roguelike', 'Roguelike', 'Roguelike', '肉鸽'),
  ('RPG', 'RPG', 'RPG', 'RPG', 'Rollenspiel', '角色扮演'),
  ('Sandbox', 'Sandbox', 'Sandbox', 'Bac à sable', 'Sandbox', '沙盒'),
  ('Shooter', 'Tiros', 'Disparos', 'Tir', 'Shooter', '射击'),
  ('Simulation', 'Simulação', 'Simulación', 'Simulation', 'Simulation', '模拟'),
  ('Sports', 'Desporto', 'Deportes', 'Sport', 'Sport', '体育'),
  ('Stealth', 'Furtividade', 'Sigilo', 'Infiltration', 'Schleichen', '潜行'),
  ('Strategy', 'Estratégia', 'Estrategia', 'Stratégie', 'Strategie', '策略'),
  ('Survival', 'Sobrevivência', 'Supervivencia', 'Survie', 'Überleben', '生存'),
  ('Tower defense', 'Defesa de torres', 'Defensa de torres', 'Tower defense', 'Tower Defense', '塔防'),
  ('Board game', 'Jogo de tabuleiro', 'Juego de mesa', 'Jeu de plateau', 'Brettspiel', '桌游'),
  ('Card game', 'Jogo de cartas', 'Juego de cartas', 'Jeu de cartes', 'Kartenspiel', '卡牌'),
  ('Educational', 'Educativo', 'Educativo', 'Éducatif', 'Lernspiel', '教育'),
  ('Multiplayer', 'Multijogador', 'Multijugador', 'Multijoueur', 'Mehrspieler', '多人'),
  ('Party', 'Festa', 'Fiesta', 'Fête', 'Party', '派对'),
  ('Quiz', 'Quiz', 'Quiz', 'Quiz', 'Quiz', '问答'),
  ('Text-based', 'Em texto', 'De texto', 'Textuel', 'Textbasiert', '文字'),
  ('Word game', 'Jogo de palavras', 'Juego de palabras', 'Jeu de mots', 'Wortspiel', '文字游戏'),
  ('Comedy', 'Comédia', 'Comedia', 'Comédie', 'Komödie', '喜剧'),
  ('Fantasy', 'Fantasia', 'Fantasía', 'Fantasy', 'Fantasy', '奇幻'),
  ('Horror', 'Terror', 'Terror', 'Horreur', 'Horror', '恐怖'),
  ('Mystery', 'Mistério', 'Misterio', 'Mystère', 'Rätselkrimi', '悬疑'),
  ('Pixel art', 'Pixel art', 'Pixel art', 'Pixel art', 'Pixel-Art', '像素'),
  ('Sci-fi', 'Ficção científica', 'Ciencia ficción', 'Science-fiction', 'Science-Fiction', '科幻'),
  ('Space', 'Espaço', 'Espacio', 'Espace', 'Weltraum', '太空'),
  ('Story', 'História', 'Historia', 'Histoire', 'Geschichte', '剧情'),
  # ---------- game page ----------
  ('← Back', '← Voltar', '← Volver', '← Retour', '← Zurück', '← 返回'),
  ('Restart', 'Recomeçar', 'Reiniciar', 'Recommencer', 'Neustart', '重新开始'),
  ('Open alone ↗', 'Abrir sozinho ↗', 'Abrir aparte ↗', 'Ouvrir à part ↗', 'Einzeln öffnen ↗', '单独打开 ↗'),
  ('Fullscreen', 'Ecrã inteiro', 'Pantalla completa', 'Plein écran', 'Vollbild', '全屏'),
  ('Your nickname', 'A tua alcunha', 'Tu apodo', 'Ton pseudo', 'Dein Spitzname', '你的昵称'),
  ('Nickname for the leaderboard', 'Alcunha para a classificação', 'Apodo para la clasificación', 'Pseudo pour le classement', 'Spitzname für die Bestenliste', '排行榜昵称'),
  ('Save score', 'Guardar pontuação', 'Guardar puntuación', 'Enregistrer le score', 'Punkte speichern', '保存分数'),
  ('No thanks', 'Não, obrigado', 'No, gracias', 'Non merci', 'Nein danke', '不用了'),
  ('Game', 'Jogo', 'Juego', 'Jeu', 'Spiel', '游戏'),
  ('Play', 'Jogar', 'Jugar', 'Jouer', 'Spielen', '开玩'),
  ('Play early build', 'Jogar versão inicial', 'Jugar versión temprana', 'Jouer à la première version', 'Frühe Version spielen', '试玩早期版本'),
  ('Stoke', 'Atiçar', 'Avivar', 'Attiser', 'Anfachen', '添柴'),
  ('Stoked', 'Atiçado', 'Avivado', 'Attisé', 'Angefacht', '已添柴'),
  ('Favorite', 'Favorito', 'Favorito', 'Favori', 'Favorit', '收藏'),
  ('Favorited', 'Nos favoritos', 'En favoritos', 'En favori', 'Favorisiert', '已收藏'),
  ('Share', 'Partilhar', 'Compartir', 'Partager', 'Teilen', '分享'),
  ('Another random game', 'Outro jogo ao calhas', 'Otro juego al azar', 'Un autre jeu au hasard', 'Ein anderes Zufallsspiel', '随机换一个游戏'),
  ('Another game', 'Outro jogo', 'Otro juego', 'Un autre jeu', 'Anderes Spiel', '换个游戏'),
  ('Open in a new tab ↗', 'Abrir num novo separador ↗', 'Abrir en una pestaña nueva ↗', 'Ouvrir dans un nouvel onglet ↗', 'In neuem Tab öffnen ↗', '在新标签页打开 ↗'),
  ('Opens on another site', 'Abre noutro site', 'Se abre en otro sitio', 'S’ouvre sur un autre site', 'Öffnet sich auf einer anderen Seite', '在其他网站打开'),
  ('I liked it', 'Gostei', 'Me gustó', 'J’ai aimé', 'Hat mir gefallen', '我喜欢'),
  ('Not for me', 'Não é para mim', 'No es para mí', 'Pas pour moi', 'Nicht mein Ding', '不适合我'),
  ('Pick thumbs up or down, or write a note.', 'Escolhe polegar para cima ou para baixo, ou escreve uma nota.', 'Elige pulgar arriba o abajo, o escribe una nota.', 'Choisis pouce en haut ou en bas, ou écris un mot.', 'Wähle Daumen hoch oder runter, oder schreib eine Notiz.', '请选择赞或踩，或者写一句话。'),
  ('Sending…', 'A enviar…', 'Enviando…', 'Envoi…', 'Wird gesendet…', '发送中…'),
  ('That didn’t send. Try again in a moment.', 'Não foi enviado. Tenta outra vez daqui a pouco.', 'No se envió. Inténtalo de nuevo en un momento.', 'Ça n’est pas parti. Réessaie dans un moment.', 'Das wurde nicht gesendet. Versuch es gleich noch mal.', '没有发送成功，请稍后再试。'),
  ('Leaderboard', 'Classificação', 'Clasificación', 'Classement', 'Bestenliste', '排行榜'),
  ('top 10', 'top 10', 'top 10', 'top 10', 'Top 10', '前 10 名'),
  ('fastest wins', 'o mais rápido ganha', 'gana el más rápido', 'le plus rapide gagne', 'die Schnellsten gewinnen', '最快者胜'),
  ('longest wins', 'o mais longo ganha', 'gana el más largo', 'le plus long gagne', 'die Längsten gewinnen', '最久者胜'),
  ('lowest wins', 'o mais baixo ganha', 'gana el más bajo', 'le plus bas gagne', 'die Niedrigsten gewinnen', '最低者胜'),
  ('No scores yet. Finish a game to be the first on the board!', 'Ainda não há pontuações. Acaba um jogo para seres o primeiro!', 'Aún no hay puntuaciones. ¡Termina una partida para ser el primero!', 'Pas encore de scores. Finis une partie pour être le premier !', 'Noch keine Punkte. Beende ein Spiel und sei der Erste auf der Liste!', '还没有分数。完成一局，成为第一名吧！'),
  ('Founder pick', 'Escolha dos fundadores', 'Elegido por los fundadores', 'Choix des fondateurs', 'Tipp der Gründer', '创始人推荐'),
  ('What’s new:', 'Novidades:', 'Novedades:', 'Nouveautés :', 'Neu:', '更新内容：'),
  ('Score:', 'Pontuação:', 'Puntuación:', 'Score :', 'Punkte:', '分数：'),
  ('. Put it on the leaderboard?', '. Pôr na classificação?', '. ¿Ponerla en la clasificación?', '. L’ajouter au classement ?', '. Auf die Bestenliste setzen?', '。要上排行榜吗？'),
  ('Saved! Not in the top 10 yet. Keep going!', 'Guardado! Ainda não estás no top 10. Continua!', '¡Guardado! Aún no estás en el top 10. ¡Sigue así!', 'Enregistré ! Pas encore dans le top 10. Continue !', 'Gespeichert! Noch nicht in den Top 10. Weiter so!', '已保存！还没进前 10 名，继续加油！'),
  ('Nicknames: 2–16 letters, numbers, spaces, - or _. No real full names!', 'Alcunhas: 2–16 letras, números, espaços, - ou _. Nada de nomes completos verdadeiros!', 'Apodos: 2–16 letras, números, espacios, - o _. ¡Nada de nombres completos reales!', 'Pseudos : 2–16 lettres, chiffres, espaces, - ou _. Pas de vrais noms complets !', 'Spitznamen: 2–16 Buchstaben, Zahlen, Leerzeichen, - oder _. Keine echten vollen Namen!', '昵称：2–16 个字母、数字、空格、- 或 _。不要用真实全名！'),
  ('Link copied. Paste it to a friend!', 'Link copiado. Cola-o para um amigo!', 'Enlace copiado. ¡Pégaselo a un amigo!', 'Lien copié. Colle-le à un ami !', 'Link kopiert. Schick ihn einem Freund!', '链接已复制，发给朋友吧！'),
  ('Copy this link:', 'Copia este link:', 'Copia este enlace:', 'Copie ce lien :', 'Kopiere diesen Link:', '复制这个链接：'),
  ('Removed from favorites.', 'Removido dos favoritos.', 'Quitado de favoritos.', 'Retiré des favoris.', 'Aus den Favoriten entfernt.', '已从收藏中移除。'),
  ('to your favorites.', 'aos teus favoritos.', 'a tus favoritos.', 'à tes favoris.', 'zu deinen Favoriten hinzugefügt.', '已加入收藏。'),
  ('You stoked', 'Atiçaste', 'Avivaste', 'Tu as attisé', 'Du hast angefacht:', '你给'),
  ('Stoke taken back from', 'Atiçada retirada de', 'Avivada retirada de', 'Flamme retirée de', 'Anfachen zurückgenommen bei', '已撤回添柴：'),
  ('Glad you played', 'Ainda bem que jogaste', 'Qué bien que jugaste', 'Content que tu aies joué à', 'Schön, dass du gespielt hast:', '很高兴你玩了'),
  ('UsForge is free, with no ads, made by four friends and a community of game makers. If you’d like to say thanks, a small tip helps keep it going.', 'O UsForge é grátis, sem anúncios, feito por quatro amigos e uma comunidade de criadores de jogos. Se quiseres agradecer, uma pequena gorjeta ajuda a mantê-lo.', 'UsForge es gratis, sin anuncios, hecho por cuatro amigos y una comunidad de creadores. Si quieres dar las gracias, una pequeña propina ayuda a mantenerlo.', 'UsForge est gratuit, sans pub, fait par quatre amis et une communauté de créateurs. Si tu veux dire merci, un petit pourboire aide à le faire vivre.', 'UsForge ist kostenlos und ohne Werbung, gemacht von vier Freunden und einer Community von Spielemachern. Wenn du Danke sagen willst, hilft ein kleines Trinkgeld.', 'UsForge 免费且无广告，由四个朋友和一群游戏创作者制作。如果你想表示感谢，一点小费能帮它继续下去。'),
  ('Leave a tip', 'Deixar uma gorjeta', 'Dejar una propina', 'Laisser un pourboire', 'Trinkgeld geben', '打赏'),
  ('Maybe later', 'Talvez depois', 'Quizás luego', 'Peut-être plus tard', 'Vielleicht später', '以后再说'),
  ('This game isn’t available in {lang}. It’s in {list}.', 'Este jogo não está disponível em {lang}. Está em {list}.', 'Este juego no está disponible en {lang}. Está en {list}.', 'Ce jeu n’est pas disponible en {lang}. Il est en {list}.', 'Dieses Spiel gibt es nicht auf {lang}. Es ist auf {list}.', '这个游戏没有{lang}版本，它只有：{list}。'),
  ('This game doesn’t have language selection, so it may only be in English.', 'Este jogo não tem escolha de idioma, por isso pode estar só em inglês.', 'Este juego no tiene selección de idioma, así que puede que solo esté en inglés.', 'Ce jeu n’a pas de choix de langue, il est peut-être seulement en anglais.', 'Dieses Spiel hat keine Sprachauswahl, es ist also vielleicht nur auf Englisch.', '这个游戏没有语言选择，可能只有英文。'),
  # ---------- credits & makers ----------
  ('UsForge was started by', 'O UsForge foi começado pela', 'UsForge fue creado por', 'UsForge a été lancé par', 'UsForge wurde gestartet von', 'UsForge 由'),
  (', four friends making games, mostly in an afternoon. Now it’s a community.', ', quatro amigos a fazer jogos, quase sempre numa tarde. Agora é uma comunidade.', ', cuatro amigos haciendo juegos, casi siempre en una tarde. Ahora es una comunidad.', ', quatre amis qui font des jeux, souvent en un après-midi. Maintenant c’est une communauté.', ', vier Freunden, die Spiele machen, meist an einem Nachmittag. Jetzt ist es eine Community.', '创立，四个朋友做游戏，通常一个下午就做好。如今它是一个社区。'),
  ('Founders', 'Fundadores', 'Fundadores', 'Fondateurs', 'Gründer', '创始人'),
  ('Director', 'Diretor', 'Director', 'Directeur', 'Direktor', '总监'),
  ('Leader', 'Líder', 'Líder', 'Chef', 'Leiter', '领队'),
  ('Developer', 'Programador', 'Desarrollador', 'Développeur', 'Entwickler', '开发者'),
  ('Quality Control', 'Controlo de qualidade', 'Control de calidad', 'Contrôle qualité', 'Qualitätskontrolle', '质量把关'),
  ('Ideas', 'Ideias', 'Ideas', 'Idées', 'Ideen', '创意'),
  ('Designer', 'Designer', 'Diseñador', 'Designer', 'Designer', '设计师'),
  ('Composer', 'Compositor', 'Compositor', 'Compositeur', 'Komponist', '作曲'),
  ('Potato', 'Batata', 'Patata', 'Patate', 'Kartoffel', '土豆'),
  ('Marketing', 'Marketing', 'Marketing', 'Marketing', 'Marketing', '宣传'),
  ('Click me', 'Clica em mim', 'Haz clic', 'Clique-moi', 'Klick mich', '点我'),
  ('Community', 'Comunidade', 'Comunidad', 'Communauté', 'Community', '社区'),
  ('Makers who joined after the founders.', 'Criadores que se juntaram depois dos fundadores.', 'Creadores que se unieron después de los fundadores.', 'Les créateurs arrivés après les fondateurs.', 'Macher, die nach den Gründern dazukamen.', '在创始人之后加入的创作者。'),
  ('first game coming soon', 'primeiro jogo em breve', 'primer juego muy pronto', 'premier jeu bientôt', 'erstes Spiel kommt bald', '第一个游戏即将推出'),
  ('The rest of the crew', 'O resto da equipa', 'El resto del equipo', 'Le reste de l’équipe', 'Der Rest der Crew', '其他成员'),
  ('Credits →', 'Créditos →', 'Créditos →', 'Crédits →', 'Credits →', '制作人员 →'),
  ('Favorite game on UsForge:', 'Jogo favorito no UsForge:', 'Juego favorito en UsForge:', 'Jeu préféré sur UsForge :', 'Lieblingsspiel auf UsForge:', '在 UsForge 最喜欢的游戏：'),
  ('No games on UsForge yet. The first one is coming soon.', 'Ainda não há jogos no UsForge. O primeiro vem a caminho.', 'Aún no hay juegos en UsForge. El primero llega pronto.', 'Pas encore de jeux sur UsForge. Le premier arrive bientôt.', 'Noch keine Spiele auf UsForge. Das erste kommt bald.', 'UsForge 上还没有游戏，第一个即将推出。'),
  # ---------- support & thanks ----------
  ('Keep the forge burning.', 'Mantém a forja acesa.', 'Mantén la forja encendida.', 'Garde la forge allumée.', 'Halte die Schmiede am Brennen.', '让熔炉继续燃烧。'),
  ('UsForge is free, with no ads and no sign-ups for players. It was started by four friends at', 'O UsForge é grátis, sem anúncios e sem registos para quem joga. Foi começado por quatro amigos na', 'UsForge es gratis, sin anuncios ni registros para los jugadores. Lo crearon cuatro amigos en', 'UsForge est gratuit, sans pub et sans inscription pour les joueurs. Il a été lancé par quatre amis chez', 'UsForge ist kostenlos, ohne Werbung und ohne Anmeldung für Spieler. Gestartet haben es vier Freunde bei', 'UsForge 对玩家免费、无广告、无需注册。它由四个朋友在'),
  (', and it’s now a community of game makers. If you’ve enjoyed a game here, a tip helps us keep making more.', ', e agora é uma comunidade de criadores de jogos. Se gostaste de um jogo aqui, uma gorjeta ajuda-nos a fazer mais.', ', y ahora es una comunidad de creadores de juegos. Si te ha gustado algún juego, una propina nos ayuda a hacer más.', ', et c’est maintenant une communauté de créateurs. Si un jeu t’a plu, un pourboire nous aide à en faire d’autres.', ', und jetzt ist es eine Community von Spielemachern. Wenn dir ein Spiel hier gefallen hat, hilft uns ein Trinkgeld, mehr zu machen.', '创立，如今是一个游戏创作者社区。如果你喜欢这里的游戏，打赏能帮我们做更多。'),
  ('Every game on UsForge stays free to play.', 'Todos os jogos no UsForge continuam grátis.', 'Todos los juegos de UsForge siguen siendo gratis.', 'Tous les jeux sur UsForge restent gratuits.', 'Jedes Spiel auf UsForge bleibt kostenlos.', 'UsForge 上的每个游戏都保持免费。'),
  ('Tips go to Lazy Studios, the founders: Taurus, Henrique, Alex and Igor.', 'As gorjetas vão para a Lazy Studios, os fundadores: Taurus, Henrique, Alex e Igor.', 'Las propinas van a Lazy Studios, los fundadores: Taurus, Henrique, Alex e Igor.', 'Les pourboires vont à Lazy Studios, les fondateurs : Taurus, Henrique, Alex et Igor.', 'Trinkgelder gehen an Lazy Studios, die Gründer: Taurus, Henrique, Alex und Igor.', '打赏归 Lazy Studios 的创始人：Taurus、Henrique、Alex 和 Igor。'),
  ('Part of every tip goes into a UsForge fund for site costs and prizes for our community game makers.', 'Parte de cada gorjeta vai para um fundo do UsForge para custos do site e prémios para os criadores da comunidade.', 'Parte de cada propina va a un fondo de UsForge para los costes del sitio y premios para los creadores de la comunidad.', 'Une partie de chaque pourboire va dans un fonds UsForge pour les frais du site et des prix pour les créateurs de la communauté.', 'Ein Teil jedes Trinkgelds geht in einen UsForge-Fonds für Seitenkosten und Preise für die Spielemacher der Community.', '每笔打赏的一部分会进入 UsForge 基金，用于网站开销和奖励社区创作者。'),
  ('1.5% of every tip helps remove CO₂ from the air, through Stripe Climate.', '1,5% de cada gorjeta ajuda a retirar CO₂ do ar, através do Stripe Climate.', 'El 1,5 % de cada propina ayuda a quitar CO₂ del aire, a través de Stripe Climate.', '1,5 % de chaque pourboire aide à retirer du CO₂ de l’air, via Stripe Climate.', '1,5 % jedes Trinkgelds helfen über Stripe Climate, CO₂ aus der Luft zu holen.', '每笔打赏的 1.5% 通过 Stripe Climate 帮助清除空气中的二氧化碳。'),
  ('Any amount you like. You choose it on the next page.', 'O valor que quiseres. Escolhes na página seguinte.', 'La cantidad que quieras. La eliges en la página siguiente.', 'Le montant que tu veux. Tu le choisis à la page suivante.', 'Jeder Betrag, den du willst. Du wählst ihn auf der nächsten Seite.', '金额随意，在下一页选择。'),
  ('What a tip helps with', 'Para que serve uma gorjeta', 'Para qué sirve una propina', 'À quoi sert un pourboire', 'Wobei ein Trinkgeld hilft', '打赏能帮上什么'),
  ('A thank-you that tells the founders people enjoy what they make.', 'Um obrigado que mostra aos fundadores que as pessoas gostam do que fazem.', 'Un gracias que les dice a los fundadores que a la gente le gusta lo que hacen.', 'Un merci qui montre aux fondateurs que les gens aiment ce qu’ils font.', 'Ein Dankeschön, das den Gründern zeigt, dass Leute mögen, was sie machen.', '一句感谢，让创始人知道大家喜欢他们的作品。'),
  ('Goes toward a prize for a community game maker.', 'Ajuda a pagar um prémio para um criador da comunidade.', 'Ayuda a pagar un premio para un creador de la comunidad.', 'Aide à financer un prix pour un créateur de la communauté.', 'Fließt in einen Preis für einen Spielemacher aus der Community.', '用于奖励一位社区创作者。'),
  ('Could pay for UsForge’s very own web address for a whole year.', 'Pode pagar um endereço próprio para o UsForge durante um ano inteiro.', 'Podría pagar una dirección web propia para UsForge durante todo un año.', 'Pourrait payer une adresse web rien qu’à UsForge pendant un an.', 'Könnte eine eigene Webadresse für UsForge für ein ganzes Jahr bezahlen.', '可以支付 UsForge 自己的网址一整年的费用。'),
  ('Most players never tip, and that’s completely fine. UsForge stays free for everyone either way.', 'A maioria dos jogadores nunca dá gorjeta, e não faz mal nenhum. O UsForge continua grátis para todos.', 'La mayoría de jugadores nunca deja propina, y no pasa nada. UsForge sigue gratis para todos.', 'La plupart des joueurs ne laissent jamais de pourboire, et c’est très bien. UsForge reste gratuit pour tout le monde.', 'Die meisten Spieler geben nie Trinkgeld, und das ist völlig okay. UsForge bleibt für alle kostenlos.', '大多数玩家从不打赏，这完全没关系。UsForge 对所有人都免费。'),
  ('Leave a tip ↗', 'Deixar uma gorjeta ↗', 'Dejar una propina ↗', 'Laisser un pourboire ↗', 'Trinkgeld geben ↗', '打赏 ↗'),
  ('Tips aren’t switched on yet. Check back soon!', 'As gorjetas ainda não estão ligadas. Volta em breve!', 'Las propinas aún no están activadas. ¡Vuelve pronto!', 'Les pourboires ne sont pas encore activés. Reviens bientôt !', 'Trinkgeld ist noch nicht eingeschaltet. Schau bald wieder vorbei!', '打赏功能还没开启，请稍后再来！'),
  ('Payments are handled securely by Stripe, so we never see your card details. If you’re under 18, please ask a parent first. Tips are a thank-you, not a charity donation, and they aren’t refundable.', 'Os pagamentos são tratados com segurança pela Stripe, por isso nunca vemos os dados do teu cartão. Se tens menos de 18 anos, pede primeiro a um pai ou mãe. As gorjetas são um agradecimento, não um donativo de caridade, e não são reembolsáveis.', 'Los pagos los gestiona Stripe de forma segura, así que nunca vemos los datos de tu tarjeta. Si tienes menos de 18 años, pregunta primero a tus padres. Las propinas son un agradecimiento, no una donación benéfica, y no se reembolsan.', 'Les paiements sont gérés en toute sécurité par Stripe, donc on ne voit jamais les infos de ta carte. Si tu as moins de 18 ans, demande d’abord à un parent. Les pourboires sont un merci, pas un don caritatif, et ne sont pas remboursables.', 'Zahlungen laufen sicher über Stripe, wir sehen also nie deine Kartendaten. Wenn du unter 18 bist, frag bitte zuerst deine Eltern. Trinkgelder sind ein Dankeschön, keine Spende, und werden nicht erstattet.', '付款由 Stripe 安全处理，我们看不到你的银行卡信息。如果你未满 18 岁，请先问问父母。打赏是一份感谢，不是慈善捐款，不可退款。'),
  ('Thank you', 'Obrigado', 'Gracias', 'Merci', 'Danke', '谢谢'),
  ('You stoked the forge.', 'Atiçaste a forja.', 'Avivaste la forja.', 'Tu as attisé la forge.', 'Du hast die Schmiede angefacht.', '你为熔炉添了柴。'),
  ('Your tip went through, and Lazy Studios says thank you! Stripe will email you a receipt.', 'A tua gorjeta chegou, e a Lazy Studios agradece! A Stripe vai enviar-te um recibo por email.', '¡Tu propina llegó y Lazy Studios te da las gracias! Stripe te enviará un recibo por correo.', 'Ton pourboire est passé, et Lazy Studios te dit merci ! Stripe t’enverra un reçu par email.', 'Dein Trinkgeld ist angekommen, und Lazy Studios sagt danke! Stripe schickt dir eine Quittung per E-Mail.', '打赏成功，Lazy Studios 谢谢你！Stripe 会把收据发到你的邮箱。'),
  ('Meet the team', 'Conhece a equipa', 'Conoce al equipo', 'Rencontre l’équipe', 'Lerne das Team kennen', '认识团队'),
  # ---------- settings ----------
  ('Make UsForge yours. These are saved in this browser only.', 'Torna o UsForge teu. Isto fica guardado só neste navegador.', 'Haz tuyo UsForge. Se guarda solo en este navegador.', 'Fais d’UsForge le tien. C’est enregistré seulement dans ce navigateur.', 'Mach UsForge zu deinem. Das wird nur in diesem Browser gespeichert.', '让 UsForge 成为你的风格。这些设置只保存在此浏览器中。'),
  ('Theme colour', 'Cor do tema', 'Color del tema', 'Couleur du thème', 'Designfarbe', '主题颜色'),
  ('Buttons, links, glows and sparks all follow it.', 'Botões, links, brilhos e faíscas seguem esta cor.', 'Botones, enlaces, brillos y chispas siguen este color.', 'Boutons, liens, lueurs et étincelles la suivent.', 'Knöpfe, Links, Leuchten und Funken folgen ihr.', '按钮、链接、光晕和火花都会跟随它。'),
  ('Blue (default)', 'Azul (padrão)', 'Azul (por defecto)', 'Bleu (par défaut)', 'Blau (Standard)', '蓝色（默认）'),
  ('Blue', 'Azul', 'Azul', 'Bleu', 'Blau', '蓝色'),
  ('Ember', 'Brasa', 'Brasa', 'Braise', 'Glut', '余烬'),
  ('Green', 'Verde', 'Verde', 'Vert', 'Grün', '绿色'),
  ('Teal', 'Azul-petróleo', 'Verde azulado', 'Bleu canard', 'Petrol', '青色'),
  ('Purple', 'Roxo', 'Morado', 'Violet', 'Lila', '紫色'),
  ('Pink', 'Rosa', 'Rosa', 'Rose', 'Rosa', '粉色'),
  ('Gold', 'Dourado', 'Dorado', 'Or', 'Gold', '金色'),
  ('Red', 'Vermelho', 'Rojo', 'Rouge', 'Rot', '红色'),
  ('Pick any colour', 'Escolhe qualquer cor', 'Elige cualquier color', 'Choisis n’importe quelle couleur', 'Wähle eine beliebige Farbe', '选择任意颜色'),
  ('Any colour…', 'Qualquer cor…', 'Cualquier color…', 'N’importe quelle couleur…', 'Beliebige Farbe…', '任意颜色…'),
  ('Back to default', 'Voltar ao padrão', 'Volver al predeterminado', 'Revenir par défaut', 'Zurück zum Standard', '恢复默认'),
  ('a link', 'um link', 'un enlace', 'un lien', 'ein Link', '一个链接'),
  ('Light or dark', 'Claro ou escuro', 'Claro u oscuro', 'Clair ou sombre', 'Hell oder dunkel', '浅色或深色'),
  ('Auto is light from 7am to 7pm, and dark the rest of the day.', 'Auto é claro das 7h às 19h, e escuro no resto do dia.', 'Auto es claro de 7:00 a 19:00, y oscuro el resto del día.', 'Auto est clair de 7 h à 19 h, et sombre le reste du temps.', 'Auto ist von 7 bis 19 Uhr hell und den Rest des Tages dunkel.', '自动模式在早 7 点到晚 7 点为浅色，其余时间为深色。'),
  ('Install UsForge so it opens in its own window, with its own icon.', 'Instala o UsForge para abrir na sua própria janela, com o seu ícone.', 'Instala UsForge para que se abra en su propia ventana, con su propio icono.', 'Installe UsForge pour qu’il s’ouvre dans sa propre fenêtre, avec sa propre icône.', 'Installiere UsForge, damit es in einem eigenen Fenster mit eigenem Symbol öffnet.', '安装 UsForge，让它在独立窗口中打开，并有自己的图标。'),
  ('This browser can’t install sites as apps. Open UsForge in', 'Este navegador não consegue instalar sites como apps. Abre o UsForge no', 'Este navegador no puede instalar sitios como apps. Abre UsForge en', 'Ce navigateur ne peut pas installer de sites comme apps. Ouvre UsForge dans', 'Dieser Browser kann Seiten nicht als App installieren. Öffne UsForge in', '此浏览器无法将网站安装为应用。请在'),
  ('or', 'ou', 'o', 'ou', 'oder', '或'),
  ('to install it.', 'para o instalar.', 'para instalarlo.', 'pour l’installer.', ', um es zu installieren.', '中打开 UsForge 来安装。'),
  ('Install UsForge', 'Instalar o UsForge', 'Instalar UsForge', 'Installer UsForge', 'UsForge installieren', '安装 UsForge'),
  ('Effects', 'Efeitos', 'Efectos', 'Effets', 'Effekte', '特效'),
  ('Sparks drifting in the background', 'Faíscas a flutuar no fundo', 'Chispas flotando en el fondo', 'Des étincelles qui flottent en arrière-plan', 'Funken, die im Hintergrund schweben', '背景中飘动的火花'),
  ('Background sparks', 'Faíscas de fundo', 'Chispas de fondo', 'Étincelles de fond', 'Hintergrund-Funken', '背景火花'),
  ('On', 'Ligado', 'Sí', 'Oui', 'An', '开'),
  ('Off', 'Desligado', 'No', 'Non', 'Aus', '关'),
  ('Game covers tilt toward your mouse', 'As capas dos jogos inclinam-se para o rato', 'Las portadas se inclinan hacia el ratón', 'Les couvertures penchent vers ta souris', 'Spielcover neigen sich zur Maus', '游戏封面随鼠标倾斜'),
  ('Card tilt', 'Inclinação das capas', 'Inclinación de portadas', 'Inclinaison des cartes', 'Karten-Neigung', '卡片倾斜'),
  # ---------- your page ----------
  ('Your UsForge', 'O teu UsForge', 'Tu UsForge', 'Ton UsForge', 'Dein UsForge', '我的 UsForge'),
  ('Your favorites, play time and badges. Saved in this browser only, no account needed.', 'Os teus favoritos, tempo de jogo e medalhas. Guardados só neste navegador, sem conta.', 'Tus favoritos, tiempo de juego e insignias. Guardado solo en este navegador, sin cuenta.', 'Tes favoris, ton temps de jeu et tes badges. Enregistrés dans ce navigateur seulement, sans compte.', 'Deine Favoriten, Spielzeit und Abzeichen. Nur in diesem Browser gespeichert, kein Konto nötig.', '你的收藏、游戏时长和徽章。只保存在此浏览器中，无需账号。'),
  ('Badges', 'Medalhas', 'Insignias', 'Badges', 'Abzeichen', '徽章'),
  ('Favorites', 'Favoritos', 'Favoritos', 'Favoris', 'Favoriten', '收藏'),
  ('tap', 'toca em', 'pulsa', 'appuie sur', 'tippe auf', '点击'),
  ('Favorite on a game’s page to add it', 'Favorito na página de um jogo para o adicionar', 'Favorito en la página de un juego para añadirlo', 'Favori sur la page d’un jeu pour l’ajouter', 'Favorit auf der Seite eines Spiels, um es hinzuzufügen', '游戏页面上的“收藏”来添加'),
  ('No favorites yet. Open a game and tap', 'Ainda não tens favoritos. Abre um jogo e toca em', 'Aún no tienes favoritos. Abre un juego y pulsa', 'Pas encore de favoris. Ouvre un jeu et appuie sur', 'Noch keine Favoriten. Öffne ein Spiel und tippe auf', '还没有收藏。打开一个游戏并点击'),
  ('Most played by you', 'Os que mais jogaste', 'Los que más has jugado', 'Ceux auxquels tu joues le plus', 'Von dir am meisten gespielt', '你玩得最多的'),
  ('Clear my UsForge data on this browser', 'Apagar os meus dados do UsForge neste navegador', 'Borrar mis datos de UsForge en este navegador', 'Effacer mes données UsForge dans ce navigateur', 'Meine UsForge-Daten in diesem Browser löschen', '清除此浏览器上的 UsForge 数据'),
  ('game played', 'jogo jogado', 'juego jugado', 'jeu joué', 'Spiel gespielt', '玩过的游戏'),
  ('games played', 'jogos jogados', 'juegos jugados', 'jeux joués', 'Spiele gespielt', '玩过的游戏'),
  ('plays', 'jogadas', 'partidas', 'parties', 'Runden', '次游玩'),
  ('played', 'jogado', 'jugado', 'joué', 'gespielt', '游戏时长'),
  ('favorites', 'favoritos', 'favoritos', 'favoris', 'Favoriten', '收藏'),
  ('day visited', 'dia de visita', 'día de visita', 'jour de visite', 'Besuchstag', '访问天数'),
  ('Nothing yet. Go play something!', 'Ainda nada. Vai jogar alguma coisa!', 'Nada todavía. ¡Ve a jugar algo!', 'Rien pour l’instant. Va jouer à quelque chose !', 'Noch nichts. Spiel doch was!', '还没有记录。快去玩点什么吧！'),
  ('days visited', 'dias de visita', 'días de visita', 'jours de visite', 'Besuchstage', '访问天数'),
  ('Earned!', 'Conquistada!', '¡Conseguida!', 'Gagné !', 'Verdient!', '已获得！'),
  ('Play any game', 'Joga um jogo qualquer', 'Juega a cualquier juego', 'Joue à n’importe quel jeu', 'Spiel irgendein Spiel', '玩任意一个游戏'),
  ('First Game', 'Primeiro jogo', 'Primer juego', 'Premier jeu', 'Erstes Spiel', '第一个游戏'),
  ('Play 5 different games', 'Joga 5 jogos diferentes', 'Juega 5 juegos distintos', 'Joue à 5 jeux différents', 'Spiel 5 verschiedene Spiele', '玩 5 个不同的游戏'),
  ('Explorer', 'Explorador', 'Explorador', 'Explorateur', 'Entdecker', '探险家'),
  ('Completionist', 'Completista', 'Completista', 'Complétiste', 'Komplettierer', '全收集'),
  ('Favorite 3 games', 'Põe 3 jogos nos favoritos', 'Marca 3 juegos como favoritos', 'Mets 3 jeux en favoris', 'Favorisiere 3 Spiele', '收藏 3 个游戏'),
  ('Collector', 'Colecionador', 'Coleccionista', 'Collectionneur', 'Sammler', '收藏家'),
  ('Play for an hour in total', 'Joga uma hora no total', 'Juega una hora en total', 'Joue une heure au total', 'Spiel insgesamt eine Stunde', '累计游玩一小时'),
  ('Marathon', 'Maratona', 'Maratón', 'Marathon', 'Marathon', '马拉松'),
  ('Play one game for 30 minutes', 'Joga um jogo durante 30 minutos', 'Juega un juego durante 30 minutos', 'Joue à un jeu pendant 30 minutes', 'Spiel ein Spiel 30 Minuten lang', '一个游戏玩 30 分钟'),
  ('Superfan', 'Superfã', 'Superfan', 'Superfan', 'Superfan', '超级粉丝'),
  ('Send feedback on 3 games', 'Dá opinião sobre 3 jogos', 'Opina sobre 3 juegos', 'Donne ton avis sur 3 jeux', 'Gib zu 3 Spielen Feedback', '给 3 个游戏反馈'),
  ('Critic', 'Crítico', 'Crítico', 'Critique', 'Kritiker', '评论家'),
  ('Stoke 5 games', 'Atiça 5 jogos', 'Aviva 5 juegos', 'Attise 5 jeux', 'Fache 5 Spiele an', '给 5 个游戏添柴'),
  ('Stoker', 'Fogueiro', 'Fogonero', 'Chauffeur', 'Heizer', '添柴人'),
  ('Visit on 5 different days', 'Visita em 5 dias diferentes', 'Visita 5 días distintos', 'Viens 5 jours différents', 'Besuche an 5 verschiedenen Tagen', '在 5 个不同的日子访问'),
  ('Regular', 'Habitual', 'Habitual', 'Habitué', 'Stammgast', '常客'),
  ('Get onto a leaderboard', 'Entra numa classificação', 'Entra en una clasificación', 'Entre dans un classement', 'Komm auf eine Bestenliste', '登上排行榜'),
  ('High Scorer', 'Recordista', 'Plusmarquista', 'As du score', 'Highscorer', '高分玩家'),
  ('Play a game after midnight', 'Joga depois da meia-noite', 'Juega después de medianoche', 'Joue après minuit', 'Spiel nach Mitternacht', '午夜后玩游戏'),
  ('Night Owl', 'Coruja noturna', 'Búho nocturno', 'Oiseau de nuit', 'Nachteule', '夜猫子'),
  ('Find the secret…', 'Descobre o segredo…', 'Encuentra el secreto…', 'Trouve le secret…', 'Finde das Geheimnis…', '找到秘密…'),
  ('Secret Potato', 'Batata secreta', 'Patata secreta', 'Patate secrète', 'Geheime Kartoffel', '神秘土豆'),
  # ---------- share your game ----------
  ('Two ways to get a game onto UsForge. Neither needs a GitHub account.', 'Duas formas de pôr um jogo no UsForge. Nenhuma precisa de conta no GitHub.', 'Dos formas de subir un juego a UsForge. Ninguna necesita cuenta de GitHub.', 'Deux façons de mettre un jeu sur UsForge. Aucune n’a besoin d’un compte GitHub.', 'Zwei Wege, ein Spiel auf UsForge zu bringen. Für keinen brauchst du ein GitHub-Konto.', '把游戏放上 UsForge 有两种方法，都不需要 GitHub 账号。'),
  ('1 · Send it to Taurus', '1 · Envia ao Taurus', '1 · Envíaselo a Taurus', '1 · Envoie-le à Taurus', '1 · Schick es an Taurus', '1 · 发给 Taurus'),
  ('2 · Upload it yourself (members)', '2 · Carrega-o tu mesmo (membros)', '2 · Súbelo tú mismo (miembros)', '2 · Publie-le toi-même (membres)', '2 · Lade es selbst hoch (Mitglieder)', '2 · 自己上传（成员）'),
  ('Join UsForge', 'Junta-te ao UsForge', 'Únete a UsForge', 'Rejoins UsForge', 'Komm zu UsForge', '加入 UsForge'),
  ('We’d love more people making games! If you make games with AI (like Claude), you can become a member and upload your own.', 'Adorávamos ter mais gente a fazer jogos! Se fazes jogos com IA (como o Claude), podes ser membro e carregar os teus.', '¡Nos encantaría que más gente hiciera juegos! Si haces juegos con IA (como Claude), puedes ser miembro y subir los tuyos.', 'On adorerait que plus de monde crée des jeux ! Si tu fais des jeux avec l’IA (comme Claude), tu peux devenir membre et publier les tiens.', 'Wir hätten gern mehr Leute, die Spiele machen! Wenn du Spiele mit KI (wie Claude) machst, kannst du Mitglied werden und deine eigenen hochladen.', '我们希望有更多人来做游戏！如果你用 AI（比如 Claude）做游戏，可以成为成员并上传自己的作品。'),
  ('Getting your game as files', 'Obter o teu jogo em ficheiros', 'Conseguir tu juego en archivos', 'Avoir ton jeu en fichiers', 'Dein Spiel als Dateien bekommen', '把游戏变成文件'),
  ('Add a leaderboard to your game', 'Junta uma classificação ao teu jogo', 'Añade una clasificación a tu juego', 'Ajoute un classement à ton jeu', 'Füge deinem Spiel eine Bestenliste hinzu', '给你的游戏加排行榜'),
  ('Make your game speak more languages', 'Põe o teu jogo a falar mais línguas', 'Haz que tu juego hable más idiomas', 'Fais parler plus de langues à ton jeu', 'Bring deinem Spiel mehr Sprachen bei', '让你的游戏支持更多语言'),
  ('UsForge can be read in English, Português, Español, Français, Deutsch and 中文, and players from all over can find your game. A game with a language menu reaches far more of them. When UsForge opens your game, it adds the player’s language to the address, like', 'O UsForge pode ser lido em English, Português, Español, Français, Deutsch e 中文, e jogadores de todo o lado podem encontrar o teu jogo. Um jogo com menu de idiomas chega a muitos mais. Quando o UsForge abre o teu jogo, junta o idioma do jogador ao endereço, assim:', 'UsForge se puede leer en English, Português, Español, Français, Deutsch y 中文, y jugadores de todas partes pueden encontrar tu juego. Un juego con menú de idiomas llega a muchos más. Cuando UsForge abre tu juego, añade el idioma del jugador a la dirección, así:', 'UsForge se lit en English, Português, Español, Français, Deutsch et 中文, et des joueurs du monde entier peuvent trouver ton jeu. Un jeu avec un menu de langues en touche bien plus. Quand UsForge ouvre ton jeu, il ajoute la langue du joueur à l’adresse, comme', 'UsForge gibt es auf English, Português, Español, Français, Deutsch und 中文, und Spieler von überall können dein Spiel finden. Ein Spiel mit Sprachmenü erreicht viel mehr von ihnen. Wenn UsForge dein Spiel öffnet, hängt es die Sprache des Spielers an die Adresse an, etwa', 'UsForge 支持 English、Português、Español、Français、Deutsch 和中文，各地的玩家都能找到你的游戏。有语言菜单的游戏能吸引更多玩家。UsForge 打开你的游戏时，会把玩家的语言加到网址里，比如'),
  ('Then tick the languages your game has on the Upload page, and they show on your game’s page. Players whose language isn’t there see a friendly heads-up. Made your game with Claude? Just ask it:', 'Depois marca as línguas do teu jogo na página Carregar, e elas aparecem na página do jogo. Quem tiver outra língua vê um aviso simpático. Fizeste o jogo com o Claude? Pede-lhe só:', 'Luego marca los idiomas de tu juego en la página Subir y aparecerán en su página. Los jugadores cuyo idioma no esté verán un aviso amable. ¿Hiciste el juego con Claude? Solo pídele:', 'Ensuite, coche les langues de ton jeu sur la page Publier, et elles s’affichent sur la page du jeu. Les joueurs dont la langue n’y est pas voient un petit avertissement. Fait avec Claude ? Demande-lui simplement :', 'Dann hake auf der Hochladen-Seite die Sprachen deines Spiels an, und sie erscheinen auf seiner Seite. Spieler, deren Sprache fehlt, sehen einen freundlichen Hinweis. Mit Claude gemacht? Frag es einfach:', '然后在上传页面勾选游戏支持的语言，它们会显示在游戏页面上。语言不在其中的玩家会看到友好的提示。用 Claude 做的游戏？直接问它：'),
  ('“Add a language menu with English and Português, and start in the language from the ?lang= part of the address.”', '“Adiciona um menu de idiomas com English e Português, e começa no idioma que vem na parte ?lang= do endereço.”', '“Añade un menú de idiomas con English y Português, y empieza en el idioma de la parte ?lang= de la dirección.”', '« Ajoute un menu de langues avec English et Português, et démarre dans la langue de la partie ?lang= de l’adresse. »', '„Füge ein Sprachmenü mit English und Português hinzu und starte in der Sprache aus dem ?lang=-Teil der Adresse.“', '“加一个包含 English 和 Português 的语言菜单，并按网址中 ?lang= 的语言启动。”'),
  ('House rules', 'Regras da casa', 'Normas de la casa', 'Règles de la maison', 'Hausregeln', '社区规则'),
  ('Only upload and change your own games.', 'Só carrega e altera os teus próprios jogos.', 'Sube y cambia solo tus propios juegos.', 'Publie et modifie seulement tes propres jeux.', 'Lade nur deine eigenen Spiele hoch und ändere nur diese.', '只上传和修改你自己的游戏。'),
  ('First names or nicknames only — no last names, photos, schools or addresses.', 'Só primeiros nomes ou alcunhas — nada de apelidos, fotos, escolas ou moradas.', 'Solo nombres de pila o apodos: nada de apellidos, fotos, colegios ni direcciones.', 'Prénoms ou pseudos seulement — pas de noms de famille, photos, écoles ou adresses.', 'Nur Vornamen oder Spitznamen — keine Nachnamen, Fotos, Schulen oder Adressen.', '只用名字或昵称——不要姓氏、照片、学校或地址。'),
  ('Nothing mean about real people.', 'Nada de maldades sobre pessoas reais.', 'Nada malo sobre personas reales.', 'Rien de méchant sur de vraies personnes.', 'Nichts Gemeines über echte Menschen.', '不要对真实的人说坏话。'),
  ('No gambling or betting games: no slots, roulette, or betting coins, gold or anything else on luck to win more. Casino-looking games without betting (like card games for points) are fine.', 'Nada de jogos de apostas: sem slots, roleta, ou apostar moedas, ouro ou outra coisa na sorte para ganhar mais. Jogos com ar de casino sem apostas (como jogos de cartas por pontos) são permitidos.', 'Nada de juegos de apuestas: ni tragaperras, ni ruleta, ni apostar monedas, oro u otra cosa a la suerte para ganar más. Los juegos con aspecto de casino sin apuestas (como cartas por puntos) están bien.', 'Pas de jeux d’argent ou de paris : pas de machines à sous, de roulette, ni de paris de pièces, d’or ou d’autre chose sur la chance pour gagner plus. Les jeux qui ressemblent à un casino sans paris (comme des jeux de cartes aux points) sont OK.', 'Keine Glücksspiele oder Wetten: keine Spielautomaten, kein Roulette, kein Setzen von Münzen, Gold oder anderem auf Glück, um mehr zu gewinnen. Casino-ähnliche Spiele ohne Wetten (wie Kartenspiele um Punkte) sind okay.', '不要赌博或押注游戏：不要老虎机、轮盘，也不要靠运气押金币、金子或其他东西来赢更多。没有押注的赌场风格游戏（比如按分数计的纸牌游戏）是可以的。'),
  ('If you want a game taken down, it comes down. No arguing.', 'Se quiseres que um jogo saia, ele sai. Sem discussões.', 'Si quieres que se quite un juego, se quita. Sin discusiones.', 'Si tu veux qu’un jeu soit retiré, il est retiré. Sans discuter.', 'Wenn du willst, dass ein Spiel entfernt wird, wird es entfernt. Ohne Diskussion.', '如果你想下架某个游戏，就会下架，不用争论。'),
  # ---------- upload ----------
  ('Account name', 'Nome da conta', 'Nombre de cuenta', 'Nom du compte', 'Kontoname', '账号名'),
  ('Password', 'Palavra-passe', 'Contraseña', 'Mot de passe', 'Passwort', '密码'),
  ('Sign in', 'Entrar', 'Entrar', 'Se connecter', 'Anmelden', '登录'),
  ('Needs review', 'Para rever', 'Por revisar', 'À vérifier', 'Zu prüfen', '待审核'),
  ('Game ideas', 'Ideias de jogos', 'Ideas de juegos', 'Idées de jeux', 'Spielideen', '游戏点子'),
  ('only members can see these', 'só os membros veem isto', 'solo los miembros pueden verlas', 'seuls les membres les voient', 'nur Mitglieder sehen das', '只有成员能看到'),
  ('Most wanted', 'Mais pedidas', 'Más deseadas', 'Les plus voulues', 'Am meisten gewünscht', '最受期待'),
  ('Post idea', 'Publicar ideia', 'Publicar idea', 'Publier l’idée', 'Idee posten', '发布点子'),
  ('Your games', 'Os teus jogos', 'Tus juegos', 'Tes jeux', 'Deine Spiele', '你的游戏'),
  ('Your profile', 'O teu perfil', 'Tu perfil', 'Ton profil', 'Dein Profil', '你的资料'),
  ('Avatar', 'Avatar', 'Avatar', 'Avatar', 'Avatar', '头像'),
  ('About you', 'Sobre ti', 'Sobre ti', 'À propos de toi', 'Über dich', '关于你'),
  ('Favorite game on UsForge', 'Jogo favorito no UsForge', 'Juego favorito en UsForge', 'Jeu préféré sur UsForge', 'Lieblingsspiel auf UsForge', '在 UsForge 最喜欢的游戏'),
  ('(none)', '(nenhum)', '(ninguno)', '(aucun)', '(keins)', '（无）'),
  ('Save profile', 'Guardar perfil', 'Guardar perfil', 'Enregistrer le profil', 'Profil speichern', '保存资料'),
  ('See your page ↗', 'Ver a tua página ↗', 'Ver tu página ↗', 'Voir ta page ↗', 'Deine Seite ansehen ↗', '查看你的页面 ↗'),
  ('Feedback', 'Opiniões', 'Opiniones', 'Avis', 'Feedback', '反馈'),
  ('Leaderboards', 'Classificações', 'Clasificaciones', 'Classements', 'Bestenlisten', '排行榜'),
  ('Add a game', 'Adicionar um jogo', 'Añadir un juego', 'Ajouter un jeu', 'Spiel hinzufügen', '添加游戏'),
  ('Game name', 'Nome do jogo', 'Nombre del juego', 'Nom du jeu', 'Spielname', '游戏名'),
  ('Folder name', 'Nome da pasta', 'Nombre de la carpeta', 'Nom du dossier', 'Ordnername', '文件夹名'),
  ('lowercase and dashes — it’s part of the game’s address', 'minúsculas e hífenes — faz parte do endereço do jogo', 'minúsculas y guiones: es parte de la dirección del juego', 'minuscules et tirets — ça fait partie de l’adresse du jeu', 'Kleinbuchstaben und Bindestriche — Teil der Spieladresse', '小写字母和短横线——会成为游戏网址的一部分'),
  ('Description', 'Descrição', 'Descripción', 'Description', 'Beschreibung', '简介'),
  ('Pixel art (keeps the cover crisp)', 'Pixel art (mantém a capa nítida)', 'Pixel art (mantiene la portada nítida)', 'Pixel art (garde la couverture nette)', 'Pixel-Art (hält das Cover scharf)', '像素风（保持封面清晰）'),
  ('Genres', 'Géneros', 'Géneros', 'Genres', 'Genres', '类型'),
  ('pick up to 3', 'escolhe até 3', 'elige hasta 3', 'choisis-en jusqu’à 3', 'wähle bis zu 3', '最多选 3 个'),
  ('which languages can your game be played in?', 'em que línguas se pode jogar o teu jogo?', '¿en qué idiomas se puede jugar tu juego?', 'dans quelles langues peut-on jouer à ton jeu ?', 'in welchen Sprachen kann man dein Spiel spielen?', '你的游戏支持哪些语言？'),
  ('Players can switch UsForge to their own language, and games in more languages reach more players: friends, family, and people in other countries. Even adding one more language makes a big difference!', 'Os jogadores podem mudar o UsForge para a sua língua, e jogos em mais línguas chegam a mais pessoas: amigos, família e gente de outros países. Até juntar só mais uma língua faz uma grande diferença!', 'Los jugadores pueden cambiar UsForge a su idioma, y los juegos en más idiomas llegan a más gente: amigos, familia y personas de otros países. ¡Incluso añadir un solo idioma más marca una gran diferencia!', 'Les joueurs peuvent passer UsForge dans leur langue, et les jeux en plusieurs langues touchent plus de monde : amis, famille et gens d’autres pays. Même ajouter une seule langue de plus change beaucoup !', 'Spieler können UsForge auf ihre Sprache umstellen, und Spiele in mehr Sprachen erreichen mehr Leute: Freunde, Familie und Menschen in anderen Ländern. Schon eine Sprache mehr macht einen großen Unterschied!', '玩家可以把 UsForge 切换成自己的语言，支持更多语言的游戏能吸引更多玩家：朋友、家人，还有其他国家的人。哪怕只多加一种语言，也会大不一样！'),
  ('Tip: your game is opened with the player’s language in its address, like', 'Dica: o teu jogo abre com a língua do jogador no endereço, assim:', 'Consejo: tu juego se abre con el idioma del jugador en la dirección, así:', 'Astuce : ton jeu s’ouvre avec la langue du joueur dans l’adresse, comme', 'Tipp: Dein Spiel wird mit der Sprache des Spielers in der Adresse geöffnet, etwa', '提示：你的游戏打开时，网址里会带上玩家的语言，比如'),
  ('. Read it with', '. Lê-a com', '. Léelo con', '. Lis-la avec', '. Lies sie mit', '。用以下代码读取：'),
  ('. Made your game with Claude? Ask it:', '. Fizeste o jogo com o Claude? Pede-lhe:', '. ¿Hiciste el juego con Claude? Pídele:', '. Fait avec Claude ? Demande-lui :', '. Mit Claude gemacht? Frag es:', '。用 Claude 做的游戏？问它：'),
  ('Still in development', 'Ainda em desenvolvimento', 'Aún en desarrollo', 'Encore en développement', 'Noch in Entwicklung', '仍在开发中'),
  ('How far along?', 'Quanto já está feito?', '¿Cuánto llevas?', 'Où en es-tu ?', 'Wie weit bist du?', '完成了多少？'),
  ('Working on next', 'A trabalhar a seguir em', 'Lo siguiente', 'Prochaine étape', 'Als Nächstes', '接下来在做'),
  ('(optional)', '(opcional)', '(opcional)', '(facultatif)', '(optional)', '（可选）'),
  ('Cover picture', 'Imagem de capa', 'Imagen de portada', 'Image de couverture', 'Coverbild', '封面图片'),
  ('Drag a picture here, or click to choose one', 'Arrasta uma imagem para aqui, ou clica para escolher', 'Arrastra una imagen aquí o haz clic para elegir una', 'Glisse une image ici, ou clique pour en choisir une', 'Zieh ein Bild hierher oder klick, um eins zu wählen', '把图片拖到这里，或点击选择'),
  ('Remove picture', 'Remover imagem', 'Quitar imagen', 'Retirer l’image', 'Bild entfernen', '移除图片'),
  ('Screenshots', 'Capturas de ecrã', 'Capturas', 'Captures d’écran', 'Screenshots', '截图'),
  ('Drag up to 4 pictures here, or click to choose', 'Arrasta até 4 imagens para aqui, ou clica para escolher', 'Arrastra hasta 4 imágenes aquí o haz clic para elegir', 'Glisse jusqu’à 4 images ici, ou clique pour choisir', 'Zieh bis zu 4 Bilder hierher oder klick zum Auswählen', '把最多 4 张图片拖到这里，或点击选择'),
  ('What’s new in this update?', 'O que há de novo nesta atualização?', '¿Qué hay de nuevo en esta actualización?', 'Quoi de neuf dans cette mise à jour ?', 'Was ist neu in diesem Update?', '这次更新有什么新内容？'),
  ('Game files', 'Ficheiros do jogo', 'Archivos del juego', 'Fichiers du jeu', 'Spieldateien', '游戏文件'),
  ('Choose a .zip', 'Escolher um .zip', 'Elegir un .zip', 'Choisir un .zip', 'Eine .zip wählen', '选择 .zip'),
  ('…or a folder', '…ou uma pasta', '…o una carpeta', '…ou un dossier', '…oder einen Ordner', '…或一个文件夹'),
  ('…or one HTML file', '…ou um ficheiro HTML', '…o un archivo HTML', '…ou un fichier HTML', '…oder eine HTML-Datei', '…或一个 HTML 文件'),
  ('…or just a link', '…ou só um link', '…o solo un enlace', '…ou juste un lien', '…oder nur einen Link', '…或只填一个链接'),
  ('Cancel update', 'Cancelar atualização', 'Cancelar actualización', 'Annuler la mise à jour', 'Update abbrechen', '取消更新'),
  ('Copy', 'Copiar', 'Copiar', 'Copier', 'Kopieren', '复制'),
  # ---------- 404 ----------
  ('Lost in the forge.', 'Perdido na forja.', 'Perdido en la forja.', 'Perdu dans la forge.', 'In der Schmiede verlaufen.', '在熔炉里迷路了。'),
  ('There’s nothing at this address. The game may have been renamed or removed, or the link has a typo.', 'Não há nada neste endereço. O jogo pode ter mudado de nome ou sido removido, ou o link tem um erro.', 'No hay nada en esta dirección. Puede que el juego cambiara de nombre o se quitara, o que el enlace tenga un error.', 'Il n’y a rien à cette adresse. Le jeu a peut-être été renommé ou retiré, ou le lien a une faute.', 'Unter dieser Adresse gibt es nichts. Das Spiel wurde vielleicht umbenannt oder entfernt, oder der Link hat einen Tippfehler.', '这个地址什么都没有。游戏可能改名或被移除了，也可能是链接写错了。'),
  ('Play something random', 'Jogar algo ao calhas', 'Jugar algo al azar', 'Jouer à un jeu au hasard', 'Etwas Zufälliges spielen', '随便玩一个'),
  ('All games →', 'Todos os jogos →', 'Todos los juegos →', 'Tous les jeux →', 'Alle Spiele →', '所有游戏 →'),
  ('Not found', 'Não encontrado', 'No encontrado', 'Introuvable', 'Nicht gefunden', '未找到'),
]

ROWS += [
  # ---------- bits of sentences that sit around a bold word or a piece of code ----------
  ('Added', 'Adicionaste', 'Añadiste', 'Tu as ajouté', 'Hinzugefügt:', '已将'),
  ('Send your game however is easiest — a', 'Envia o teu jogo da forma mais fácil — um', 'Envía tu juego como te resulte más fácil: un', 'Envoie ton jeu comme c’est le plus simple — un', 'Schick dein Spiel, wie es am einfachsten ist — eine', '用最方便的方式发送你的游戏——游戏文件夹的'),
  ('of its folder, an HTML file, or a Claude artifact link — with its name and a one-line description. Taurus puts it up.', 'da pasta, um ficheiro HTML ou um link de artefacto do Claude — com o nome e uma descrição de uma linha. O Taurus põe-no online.', 'de su carpeta, un archivo HTML o un enlace de artefacto de Claude, con su nombre y una descripción de una línea. Taurus lo publica.', 'de son dossier, un fichier HTML ou un lien d’artefact Claude — avec son nom et une description d’une ligne. Taurus le met en ligne.', 'des Ordners, eine HTML-Datei oder einen Claude-Artefakt-Link — mit Namen und einer einzeiligen Beschreibung. Taurus stellt es online.', '、一个 HTML 文件或 Claude 作品链接都可以——附上名字和一句话简介，Taurus 会把它放上去。'),
  ('If you have a UsForge account, go to', 'Se tens uma conta UsForge, vai a', 'Si tienes una cuenta de UsForge, ve a', 'Si tu as un compte UsForge, va sur', 'Wenn du ein UsForge-Konto hast, geh zu', '如果你有 UsForge 账号，前往'),
  (', sign in, pick your game’s', ', entra, escolhe o', ', inicia sesión, elige el', ', connecte-toi, choisis le', ', melde dich an, wähle die', '，登录，选择游戏的'),
  ('(or folder, or HTML file), and press Upload. A new game from a member goes live once one of the founders has checked it; updates to your games go live in about a minute. You can update or remove your own games there any time.', 'do teu jogo (ou a pasta, ou o ficheiro HTML) e carrega em Carregar. Um jogo novo de um membro fica online depois de um fundador o ver; as atualizações aparecem em cerca de um minuto. Podes atualizar ou remover os teus jogos lá a qualquer momento.', 'de tu juego (o la carpeta, o el archivo HTML) y pulsa Subir. Un juego nuevo de un miembro se publica cuando un fundador lo revisa; las actualizaciones salen en un minuto. Puedes actualizar o quitar tus juegos allí cuando quieras.', 'de ton jeu (ou le dossier, ou le fichier HTML), et appuie sur Publier. Un nouveau jeu d’un membre est en ligne dès qu’un fondateur l’a vérifié ; les mises à jour arrivent en une minute environ. Tu peux mettre à jour ou retirer tes jeux à tout moment.', 'deines Spiels (oder den Ordner oder die HTML-Datei) und drück auf Hochladen. Ein neues Spiel eines Mitglieds geht online, sobald ein Gründer es geprüft hat; Updates sind in etwa einer Minute online. Du kannst deine Spiele dort jederzeit aktualisieren oder entfernen。'.replace('。', '.'), '（或文件夹、HTML 文件），然后点击上传。成员的新游戏经创始人检查后上线；更新大约一分钟后生效。你随时可以在那里更新或删除自己的游戏。'),
  ('Go to the', 'Vai à página', 'Ve a la página', 'Va sur la page', 'Geh auf die Seite', '前往'),
  ('page and scroll to', 'e desce até', 'y baja hasta', 'et descends jusqu’à', 'und scrolle zu', '页面，滚动到'),
  ('“New member? Make your password code”', '“Novo membro? Cria o teu código de palavra-passe”', '“¿Nuevo miembro? Crea tu código de contraseña”', '« Nouveau membre ? Crée ton code de mot de passe »', '„Neues Mitglied? Erstelle deinen Passwort-Code“', '“新成员？生成你的密码码”'),
  ('Pick an account name and a password, and press the button. You get a', 'Escolhe um nome de conta e uma palavra-passe e carrega no botão. Recebes um', 'Elige un nombre de cuenta y una contraseña y pulsa el botón. Obtienes un', 'Choisis un nom de compte et un mot de passe, et appuie sur le bouton. Tu obtiens un', 'Wähle einen Kontonamen und ein Passwort und drück den Knopf. Du bekommst einen', '选一个账号名和密码，然后点按钮。你会得到一个'),
  ('password code', 'código de palavra-passe', 'código de contraseña', 'code de mot de passe', 'Passwort-Code', '密码码'),
  ('Send just that code to Taurus. It can check your password, but can’t be turned back into it, so nobody ever sees your password.', 'Envia só esse código ao Taurus. Ele serve para verificar a palavra-passe, mas não dá para a descobrir, por isso ninguém a vê.', 'Envía solo ese código a Taurus. Sirve para comprobar tu contraseña, pero no se puede convertir de vuelta en ella, así que nadie la ve nunca.', 'Envoie juste ce code à Taurus. Il permet de vérifier ton mot de passe, mais on ne peut pas retrouver le mot de passe avec, donc personne ne le voit jamais.', 'Schick nur diesen Code an Taurus. Er kann dein Passwort prüfen, lässt sich aber nicht zurückverwandeln, also sieht niemand dein Passwort.', '只把这个码发给 Taurus。它能验证你的密码，但无法反推出密码，所以没人会看到你的密码。'),
  ('Once Taurus adds you, sign in on the Upload page and share your games. Your first ones get a quick look from a founder before they go live.', 'Quando o Taurus te adicionar, entra na página Carregar e partilha os teus jogos. Os primeiros são vistos rapidamente por um fundador antes de ficarem online.', 'Cuando Taurus te añada, entra en la página Subir y comparte tus juegos. Un fundador echa un vistazo rápido a los primeros antes de publicarlos.', 'Une fois que Taurus t’a ajouté, connecte-toi sur la page Publier et partage tes jeux. Un fondateur jette un œil aux premiers avant qu’ils soient en ligne.', 'Sobald Taurus dich hinzugefügt hat, melde dich auf der Hochladen-Seite an und teile deine Spiele. Deine ersten schaut sich ein Gründer kurz an, bevor sie online gehen.', 'Taurus 添加你之后，在上传页面登录并分享你的游戏。你最初的几个游戏会先由创始人快速看一下再上线。'),
  ('A game needs an', 'Um jogo precisa de um', 'Un juego necesita un', 'Un jeu a besoin d’un', 'Ein Spiel braucht eine', '游戏需要一个'),
  ('(plus any other files it uses). If your game is a Claude artifact, ask Claude in that chat:', '(e outros ficheiros que use). Se o teu jogo é um artefacto do Claude, pede ao Claude nessa conversa:', '(y los demás archivos que use). Si tu juego es un artefacto de Claude, pídele a Claude en ese chat:', '(et les autres fichiers qu’il utilise). Si ton jeu est un artefact Claude, demande à Claude dans ce chat :', '(plus alle anderen Dateien, die es nutzt). Wenn dein Spiel ein Claude-Artefakt ist, frag Claude in diesem Chat:', '（以及它用到的其他文件）。如果你的游戏是 Claude 作品，就在那个对话里问 Claude：'),
  ('“give me this game as an HTML file I can download.”', '“dá-me este jogo como um ficheiro HTML para eu descarregar.”', '“dame este juego como un archivo HTML que pueda descargar.”', '« donne-moi ce jeu sous forme de fichier HTML à télécharger. »', '„Gib mir dieses Spiel als HTML-Datei zum Herunterladen.“', '“把这个游戏做成我能下载的 HTML 文件。”'),
  ('A link also works — the card then opens it in a new tab.', 'Um link também serve — o cartão abre-o num novo separador.', 'Un enlace también vale: la tarjeta lo abre en una pestaña nueva.', 'Un lien marche aussi — la carte l’ouvre alors dans un nouvel onglet.', 'Ein Link geht auch — die Karte öffnet ihn dann in einem neuen Tab.', '链接也可以——卡片会在新标签页中打开它。'),
  ('Game made of several files or folders?', 'O jogo tem vários ficheiros ou pastas?', '¿Tu juego tiene varios archivos o carpetas?', 'Ton jeu a plusieurs fichiers ou dossiers ?', 'Spiel aus mehreren Dateien oder Ordnern?', '游戏由多个文件或文件夹组成？'),
  ('Zip it into one file: on a Mac, right-click the game’s folder →', 'Comprime-o num só ficheiro: no Mac, clica com o botão direito na pasta →', 'Comprímelo en un solo archivo: en Mac, clic derecho en la carpeta →', 'Compresse-le en un seul fichier : sur Mac, clic droit sur le dossier →', 'Pack es in eine Datei: auf dem Mac Rechtsklick auf den Ordner →', '把它压缩成一个文件：在 Mac 上右键点击游戏文件夹 →'),
  ('Compress', 'Comprimir', 'Comprimir', 'Compresser', 'Komprimieren', '压缩'),
  ('; on Windows, right-click →', '; no Windows, botão direito →', '; en Windows, clic derecho →', ' ; sur Windows, clic droit →', '; unter Windows Rechtsklick →', '；在 Windows 上右键 →'),
  ('Send to → Compressed (zipped) folder', 'Enviar para → Pasta comprimida (zipada)', 'Enviar a → Carpeta comprimida (en zip)', 'Envoyer vers → Dossier compressé', 'Senden an → ZIP-komprimierter Ordner', '发送到 → 压缩(zipped)文件夹'),
  ('. Send or upload that', '. Envia ou carrega esse', '. Envía o sube ese', '. Envoie ou publie ce', '. Schick oder lade diese', '。发送或上传这个'),
  ('— UsForge unpacks it by itself.', '— o UsForge descomprime-o sozinho.', ': UsForge lo descomprime solo.', '— UsForge le décompresse tout seul.', '— UsForge entpackt sie von selbst.', '——UsForge 会自动解压。'),
  ('Nice extras: a screenshot named', 'Extra simpático: uma imagem chamada', 'Un extra: una captura llamada', 'Petit plus : une capture nommée', 'Schönes Extra: ein Screenshot namens', '小技巧：把截图命名为'),
  ('in the folder becomes the game’s card picture.', 'na pasta passa a ser a imagem do cartão do jogo.', 'en la carpeta se convierte en la imagen de la tarjeta.', 'dans le dossier devient l’image de la carte du jeu.', 'im Ordner wird zum Kartenbild des Spiels.', '放在文件夹里，就会成为游戏卡片的图片。'),
  ('UsForge can show a top-10 leaderboard on your game’s page. When a round ends, your game just sends its score with one line of code:', 'O UsForge pode mostrar uma classificação top 10 na página do teu jogo. Quando uma ronda acaba, o jogo só tem de enviar a pontuação com uma linha de código:', 'UsForge puede mostrar una clasificación top 10 en la página de tu juego. Cuando acaba una ronda, tu juego solo envía su puntuación con una línea de código:', 'UsForge peut afficher un classement top 10 sur la page de ton jeu. À la fin d’une partie, ton jeu envoie juste son score avec une ligne de code :', 'UsForge kann auf der Seite deines Spiels eine Top-10-Bestenliste zeigen. Am Ende einer Runde schickt dein Spiel einfach die Punkte mit einer Zeile Code:', 'UsForge 可以在你的游戏页面显示前 10 名排行榜。一局结束时，游戏只要用一行代码发送分数：'),
  ('Fewest wins, like golf or a speedrun time? Add', 'Ganha quem tem menos, como no golfe ou num speedrun? Junta', '¿Gana el que tiene menos, como en golf o un speedrun? Añade', 'Le plus petit gagne, comme au golf ou en speedrun ? Ajoute', 'Gewinnt der Niedrigste, wie beim Golf oder Speedrun? Füge', '分数越低越好，比如高尔夫或速通时间？加上'),
  ('. Want a label? Add', '. Queres uma etiqueta? Junta', '. ¿Quieres una etiqueta? Añade', '. Tu veux une unité ? Ajoute', ' hinzu. Ein Etikett? Füge', '。想要单位？加上'),
  ('. For a time, send whole seconds with', '. Para um tempo, envia segundos inteiros com', '. Para un tiempo, envía segundos enteros con', '. Pour un temps, envoie des secondes entières avec', ' hinzu. Für eine Zeit schick ganze Sekunden mit', '。如果是时间，用整秒并加上'),
  ('and UsForge shows it as a clock (like 38:12). The player then gets asked for a nickname. Made your game with Claude? Just ask it:', 'e o UsForge mostra-o como um relógio (tipo 38:12). Depois o jogador escolhe uma alcunha. Fizeste o jogo com o Claude? Pede-lhe só:', 'y UsForge lo muestra como un reloj (como 38:12). Luego se le pide un apodo al jugador. ¿Hiciste el juego con Claude? Solo pídele:', 'et UsForge l’affiche comme une horloge (comme 38:12). Le joueur choisit ensuite un pseudo. Fait avec Claude ? Demande-lui simplement :', 'und UsForge zeigt sie als Uhr (wie 38:12). Dann wird der Spieler nach einem Spitznamen gefragt. Mit Claude gemacht? Frag es einfach:', '，UsForge 会显示成时钟（比如 38:12）。然后玩家会被要求输入昵称。用 Claude 做的游戏？直接问它：'),
  ('“When the game ends, send the score to UsForge with parent.postMessage({ usforge: \'score\', score: SCORE }, \'*\').”', '“Quando o jogo acabar, envia a pontuação para o UsForge com parent.postMessage({ usforge: \'score\', score: SCORE }, \'*\').”', '“Cuando termine la partida, envía la puntuación a UsForge con parent.postMessage({ usforge: \'score\', score: SCORE }, \'*\').”', '« Quand la partie se termine, envoie le score à UsForge avec parent.postMessage({ usforge: \'score\', score: SCORE }, \'*\'). »', '„Wenn das Spiel endet, schick die Punkte an UsForge mit parent.postMessage({ usforge: \'score\', score: SCORE }, \'*\').“', '“游戏结束时，用 parent.postMessage({ usforge: \'score\', score: SCORE }, \'*\') 把分数发给 UsForge。”'),
  # ---------- upload page details ----------
  ('Members can add and update their own games here. New games from members are checked by one of the founders before they go live. Updates, and the founders’ own games, go live straight away.', 'Os membros podem adicionar e atualizar os seus jogos aqui. Os jogos novos dos membros são vistos por um fundador antes de ficarem online. As atualizações, e os jogos dos fundadores, ficam online logo.', 'Los miembros pueden añadir y actualizar sus juegos aquí. Un fundador revisa los juegos nuevos de los miembros antes de publicarlos. Las actualizaciones, y los juegos de los fundadores, se publican al instante.', 'Les membres peuvent ajouter et mettre à jour leurs jeux ici. Les nouveaux jeux des membres sont vérifiés par un fondateur avant d’être en ligne. Les mises à jour, et les jeux des fondateurs, sont en ligne tout de suite.', 'Mitglieder können hier ihre eigenen Spiele hinzufügen und aktualisieren. Neue Spiele von Mitgliedern prüft ein Gründer, bevor sie online gehen. Updates und die Spiele der Gründer gehen sofort online.', '成员可以在这里添加和更新自己的游戏。成员的新游戏会先由创始人检查再上线。更新以及创始人自己的游戏会立即上线。'),
  ('Uploading only works on the main address:', 'Carregar só funciona no endereço principal:', 'Subir solo funciona en la dirección principal:', 'La publication ne marche que sur l’adresse principale :', 'Hochladen geht nur über die Hauptadresse:', '只有在主网址上才能上传：'),
  ('New games from members wait here until one of the founders approves them.', 'Os jogos novos dos membros esperam aqui até um fundador os aprovar.', 'Los juegos nuevos de los miembros esperan aquí hasta que un fundador los apruebe.', 'Les nouveaux jeux des membres attendent ici qu’un fondateur les approuve.', 'Neue Spiele von Mitgliedern warten hier, bis ein Gründer sie freigibt.', '成员的新游戏会在这里等待创始人批准。'),
  ('Sort ideas', 'Ordenar ideias', 'Ordenar ideas', 'Trier les idées', 'Ideen sortieren', '排序点子'),
  ('Idea name, like “Ten-Second Heist”', 'Nome da ideia, tipo “Assalto de Dez Segundos”', 'Nombre de la idea, como “Atraco de diez segundos”', 'Nom de l’idée, comme « Casse en dix secondes »', 'Name der Idee, z. B. „Zehn-Sekunden-Coup“', '点子名称，比如“十秒大劫案”'),
  ('Idea name', 'Nome da ideia', 'Nombre de la idea', 'Nom de l’idée', 'Name der Idee', '点子名称'),
  ('Everyone with an account can see it, vote for it, or say they’re making it.', 'Todos com conta podem vê-la, votar nela ou dizer que a estão a fazer.', 'Todos los que tienen cuenta pueden verla, votarla o decir que la están haciendo.', 'Tous ceux qui ont un compte peuvent la voir, voter pour elle ou dire qu’ils la font.', 'Alle mit Konto können sie sehen, dafür stimmen oder sagen, dass sie sie bauen.', '有账号的人都能看到、投票，或表示自己在做。'),
  ('Shown on your maker page and in Credits. First names or nicknames only, nothing private.', 'Aparece na tua página de criador e nos Créditos. Só primeiros nomes ou alcunhas, nada privado.', 'Se muestra en tu página de creador y en Créditos. Solo nombres de pila o apodos, nada privado.', 'Affiché sur ta page de créateur et dans les Crédits. Prénoms ou pseudos seulement, rien de privé.', 'Wird auf deiner Macher-Seite und in den Credits gezeigt. Nur Vornamen oder Spitznamen, nichts Privates.', '会显示在你的创作者页面和制作人员名单中。只用名字或昵称，不要私人信息。'),
  ('What players said about your games. Only you and the founders can see this.', 'O que os jogadores disseram dos teus jogos. Só tu e os fundadores veem isto.', 'Lo que los jugadores dijeron de tus juegos. Solo tú y los fundadores podéis verlo.', 'Ce que les joueurs ont dit de tes jeux. Seuls toi et les fondateurs peuvent le voir.', 'Was Spieler über deine Spiele gesagt haben. Nur du und die Gründer sehen das.', '玩家对你游戏的评价。只有你和创始人能看到。'),
  ('Top scores on your games. Delete any nickname that’s rude or a real full name.', 'As melhores pontuações nos teus jogos. Apaga alcunhas mal-educadas ou nomes completos verdadeiros.', 'Las mejores puntuaciones de tus juegos. Borra cualquier apodo grosero o que sea un nombre completo real.', 'Les meilleurs scores de tes jeux. Supprime tout pseudo grossier ou vrai nom complet.', 'Top-Punkte in deinen Spielen. Lösche jeden Spitznamen, der gemein oder ein echter voller Name ist.', '你游戏的最高分。删除任何粗鲁的昵称或真实全名。'),
  ('Star games to show them in the “Founder picks” row on the home page.', 'Põe estrela em jogos para aparecerem na fila “Escolhas dos fundadores” na página inicial.', 'Marca juegos con estrella para que salgan en la fila “Elegidos por los fundadores” de la portada.', 'Mets une étoile aux jeux pour les afficher dans la rangée « Choix des fondateurs » de l’accueil.', 'Markiere Spiele mit einem Stern, damit sie in der Reihe „Tipps der Gründer“ auf der Startseite erscheinen.', '给游戏加星，让它们出现在首页的“创始人推荐”一栏。'),
  ('(shows in the “In development” section; you can post it before there’s anything to play)', '(aparece na secção “Em desenvolvimento”; podes publicá-lo antes de haver algo para jogar)', '(aparece en la sección “En desarrollo”; puedes publicarlo antes de que haya algo para jugar)', '(apparaît dans la section « En développement » ; tu peux le publier avant qu’il y ait de quoi jouer)', '(erscheint im Bereich „In Entwicklung“; du kannst es posten, bevor es etwas zu spielen gibt)', '（显示在“开发中”栏目；还没东西可玩时也能发布）'),
  ('(optional — shown on the game’s card)', '(opcional — aparece no cartão do jogo)', '(opcional: se ve en la tarjeta del juego)', '(facultatif — affichée sur la carte du jeu)', '(optional — erscheint auf der Spielkarte)', '（可选——显示在游戏卡片上）'),
  ('PNG, JPG, WEBP or GIF · wide pictures look best', 'PNG, JPG, WEBP ou GIF · imagens largas ficam melhor', 'PNG, JPG, WEBP o GIF · las imágenes anchas quedan mejor', 'PNG, JPG, WEBP ou GIF · les images larges rendent mieux', 'PNG, JPG, WEBP oder GIF · breite Bilder sehen am besten aus', 'PNG、JPG、WEBP 或 GIF · 宽图效果最好'),
  ('(optional — up to 4, shown on the game’s page)', '(opcional — até 4, aparecem na página do jogo)', '(opcional: hasta 4, se ven en la página del juego)', '(facultatif — jusqu’à 4, affichées sur la page du jeu)', '(optional — bis zu 4, erscheinen auf der Spielseite)', '（可选——最多 4 张，显示在游戏页面）'),
  ('Remove this game’s screenshots', 'Remover as capturas deste jogo', 'Quitar las capturas de este juego', 'Retirer les captures de ce jeu', 'Screenshots dieses Spiels entfernen', '移除这个游戏的截图'),
  ('(optional — one line, shown on the game’s page and in everyone’s notifications)', '(opcional — uma linha, aparece na página do jogo e nas notificações de todos)', '(opcional: una línea, se ve en la página del juego y en las notificaciones de todos)', '(facultatif — une ligne, affichée sur la page du jeu et dans les notifications de tous)', '(optional — eine Zeile, erscheint auf der Spielseite und in allen Benachrichtigungen)', '（可选——一句话，显示在游戏页面和大家的通知里）'),
  ('Added a boss fight and 3 new levels!', 'Juntei uma luta com um chefe e 3 níveis novos!', '¡Añadí un jefe final y 3 niveles nuevos!', 'Ajout d’un boss et de 3 nouveaux niveaux !', 'Bosskampf und 3 neue Level hinzugefügt!', '新增了首领战和 3 个新关卡！'),
  ('More levels and a boss fight', 'Mais níveis e uma luta com um chefe', 'Más niveles y un jefe final', 'Plus de niveaux et un boss', 'Mehr Level und ein Bosskampf', '更多关卡和首领战'),
  ('Dodge the forks.', 'Desvia-te dos garfos.', 'Esquiva los tenedores.', 'Évite les fourchettes.', 'Weich den Gabeln aus.', '躲开叉子。'),
  ('Nothing chosen. Zip up your game’s folder (right-click → Compress) and pick the zip. It needs an', 'Nada escolhido. Comprime a pasta do jogo (botão direito → Comprimir) e escolhe o zip. Precisa de um', 'Nada elegido. Comprime la carpeta del juego (clic derecho → Comprimir) y elige el zip. Necesita un', 'Rien de choisi. Compresse le dossier du jeu (clic droit → Compresser) et choisis le zip. Il faut un', 'Nichts gewählt. Pack den Spielordner als ZIP (Rechtsklick → Komprimieren) und wähl die ZIP. Sie braucht eine', '还没选择。把游戏文件夹压缩（右键 → 压缩）后选择 zip。它需要一个'),
  ('; a', '; uma imagem', '; una imagen', ' ; une image', '; ein', '；一张'),
  ('screenshot makes a nicer card. Up to 1,000 files and 60 MB.', 'deixa o cartão mais bonito. Até 1.000 ficheiros e 60 MB.', 'hace la tarjeta más bonita. Hasta 1.000 archivos y 60 MB.', 'rend la carte plus jolie. Jusqu’à 1 000 fichiers et 60 Mo.', 'Screenshot macht die Karte schöner. Bis zu 1.000 Dateien und 60 MB.', '截图能让卡片更好看。最多 1000 个文件、60 MB。'),
  ('(e.g. a Claude artifact link — it opens in its own tab)', '(p. ex. um link de artefacto do Claude — abre no seu próprio separador)', '(p. ej. un enlace de artefacto de Claude: se abre en su propia pestaña)', '(par ex. un lien d’artefact Claude — il s’ouvre dans son propre onglet)', '(z. B. ein Claude-Artefakt-Link — öffnet sich in einem eigenen Tab)', '（比如 Claude 作品链接——会在单独的标签页打开）'),
  ('Add a friend’s account', 'Adicionar a conta de um amigo', 'Añadir la cuenta de un amigo', 'Ajouter le compte d’un ami', 'Konto eines Freundes hinzufügen', '添加朋友的账号'),
  ('Your friend makes a password code below and sends it to you. You never see their password.', 'O teu amigo cria um código de palavra-passe aqui em baixo e envia-to. Nunca vês a palavra-passe dele.', 'Tu amigo crea un código de contraseña abajo y te lo envía. Nunca ves su contraseña.', 'Ton ami crée un code de mot de passe ci-dessous et te l’envoie. Tu ne vois jamais son mot de passe.', 'Dein Freund erstellt unten einen Passwort-Code und schickt ihn dir. Du siehst nie sein Passwort.', '你的朋友在下面生成密码码并发给你。你永远看不到他的密码。'),
  ('Their account name', 'Nome da conta dele', 'Su nombre de cuenta', 'Son nom de compte', 'Sein Kontoname', '他的账号名'),
  ('Their password code', 'Código de palavra-passe dele', 'Su código de contraseña', 'Son code de mot de passe', 'Sein Passwort-Code', '他的密码码'),
  ('Add account', 'Adicionar conta', 'Añadir cuenta', 'Ajouter le compte', 'Konto hinzufügen', '添加账号'),
  ('New member? Make your password code', 'Novo membro? Cria o teu código de palavra-passe', '¿Nuevo miembro? Crea tu código de contraseña', 'Nouveau membre ? Crée ton code de mot de passe', 'Neues Mitglied? Erstelle deinen Passwort-Code', '新成员？生成你的密码码'),
  ('Pick a password (8+ characters) and make a code from it. Send only the code to Taurus — the code can check your password, but can’t be turned back into it. This all happens on your device.', 'Escolhe uma palavra-passe (8+ caracteres) e cria um código a partir dela. Envia só o código ao Taurus — o código verifica a palavra-passe, mas não dá para a descobrir. Tudo acontece no teu dispositivo.', 'Elige una contraseña (8+ caracteres) y crea un código con ella. Envía solo el código a Taurus: sirve para comprobar tu contraseña, pero no se puede convertir de vuelta. Todo pasa en tu dispositivo.', 'Choisis un mot de passe (8 caractères ou plus) et crée un code avec. Envoie seulement le code à Taurus — il peut vérifier ton mot de passe, mais ne permet pas de le retrouver. Tout se passe sur ton appareil.', 'Wähle ein Passwort (mind. 8 Zeichen) und erstelle daraus einen Code. Schick nur den Code an Taurus — er kann dein Passwort prüfen, aber nicht zurückverwandelt werden. Alles passiert auf deinem Gerät.', '选一个密码（至少 8 个字符），用它生成一个码。只把码发给 Taurus——它能验证你的密码，但无法反推出来。这一切都在你的设备上完成。'),
  ('Your account name', 'O teu nome de conta', 'Tu nombre de cuenta', 'Ton nom de compte', 'Dein Kontoname', '你的账号名'),
  ('Password again', 'Palavra-passe outra vez', 'Repite la contraseña', 'Mot de passe encore', 'Passwort wiederholen', '再次输入密码'),
  ('Make my code', 'Criar o meu código', 'Crear mi código', 'Créer mon code', 'Meinen Code erstellen', '生成我的码'),
  ('Sending', 'A enviar', 'Enviando', 'Envoi', 'Wird gesendet', '发送中'),
]

# sentences with a name or number in them: (English regex, then the replacement in each language)
PATTERNS = [
  (r'^by (.+)$', 'por $1', 'por $1', 'par $1', 'von $1', '$1 制作'),
  (r'^Game (\d+) of (\d+)$', 'Jogo $1 de $2', 'Juego $1 de $2', 'Jeu $1 sur $2', 'Spiel $1 von $2', '第 $1 个，共 $2 个'),
  (r'^Added today$', 'Adicionado hoje', 'Añadido hoy', 'Ajouté aujourd’hui', 'Heute hinzugefügt', '今天添加'),
  (r'^Added yesterday$', 'Adicionado ontem', 'Añadido ayer', 'Ajouté hier', 'Gestern hinzugefügt', '昨天添加'),
  (r'^Added (\d+) days ago$', 'Adicionado há $1 dias', 'Añadido hace $1 días', 'Ajouté il y a $1 jours', 'Vor $1 Tagen hinzugefügt', '$1 天前添加'),
  (r'^Added (.+)$', 'Adicionado a $1', 'Añadido el $1', 'Ajouté le $1', 'Hinzugefügt am $1', '添加于 $1'),
  (r'^Updated today$', 'Atualizado hoje', 'Actualizado hoy', 'Mis à jour aujourd’hui', 'Heute aktualisiert', '今天更新'),
  (r'^Updated yesterday$', 'Atualizado ontem', 'Actualizado ayer', 'Mis à jour hier', 'Gestern aktualisiert', '昨天更新'),
  (r'^Updated (\d+) days ago$', 'Atualizado há $1 dias', 'Actualizado hace $1 días', 'Mis à jour il y a $1 jours', 'Vor $1 Tagen aktualisiert', '$1 天前更新'),
  (r'^Updated (.+)$', 'Atualizado a $1', 'Actualizado el $1', 'Mis à jour le $1', 'Aktualisiert am $1', '更新于 $1'),
  (r'^(\d+) games$', '$1 jogos', '$1 juegos', '$1 jeux', '$1 Spiele', '$1 个游戏'),
  (r'^1 game$', '1 jogo', '1 juego', '1 jeu', '1 Spiel', '1 个游戏'),
  (r'^(\d+) games? on UsForge →$', '$1 jogos no UsForge →', '$1 juegos en UsForge →', '$1 jeux sur UsForge →', '$1 Spiele auf UsForge →', 'UsForge 上的 $1 个游戏 →'),
  (r'^(\d+) games? · (\d+) in dev$', '$1 jogos · $2 em desenvolvimento', '$1 juegos · $2 en desarrollo', '$1 jeux · $2 en développement', '$1 Spiele · $2 in Entwicklung', '$1 个游戏 · $2 个开发中'),
  (r'^(\d+) plays?$', '$1 jogadas', '$1 partidas', '$1 parties', '$1 Runden', '$1 次游玩'),
  (r'^(\d+) stokes?$', '$1 atiçadas', '$1 avivadas', '$1 flammes', '$1 Anfacher', '$1 次添柴'),
  (r'^(\d+)% done$', '$1% feito', '$1 % hecho', '$1 % fait', '$1 % fertig', '已完成 $1%'),
  (r'^(.+) \((\d+)\)$', '{t:$1} ($2)', '{t:$1} ($2)', '{t:$1} ($2)', '{t:$1} ($2)', '{t:$1}（$2）'),
  (r'^What did you think of (.+)\?$', 'O que achaste de $1?', '¿Qué te pareció $1?', 'Qu’as-tu pensé de $1 ?', 'Wie fandest du $1?', '你觉得 $1 怎么样？'),
  (r'^Enjoying (.+)\?$', 'Estás a gostar de $1?', '¿Te gusta $1?', 'Tu aimes $1 ?', 'Gefällt dir $1?', '喜欢 $1 吗？'),
  (r'^Glad you played (.+)!$', 'Ainda bem que jogaste $1!', '¡Qué bien que jugaste a $1!', 'Content que tu aies joué à $1 !', 'Schön, dass du $1 gespielt hast!', '很高兴你玩了 $1！'),
  (r'^Send to (.+)$', 'Enviar a $1', 'Enviar a $1', 'Envoyer à $1', 'An $1 senden', '发给 $1'),
  (r'^Only (.+) and the founders can read this\.$', 'Só $1 e os fundadores podem ler isto.', 'Solo $1 y los fundadores pueden leer esto.', 'Seuls $1 et les fondateurs peuvent lire ceci.', 'Nur $1 und die Gründer können das lesen.', '只有 $1 和创始人能看到。'),
  (r'^Anything to tell (.+)\? \(optional\)$', 'Algo a dizer a $1? (opcional)', '¿Algo que decirle a $1? (opcional)', 'Un mot pour $1 ? (facultatif)', 'Etwas für $1? (optional)', '有什么想对 $1 说的吗？（可选）'),
  (r'^Sent! (.+) will see it on their Upload page\.$', 'Enviado! $1 vai ver na página Carregar.', '¡Enviado! $1 lo verá en su página Subir.', 'Envoyé ! $1 le verra sur sa page Publier.', 'Gesendet! $1 sieht es auf der Hochladen-Seite.', '已发送！$1 会在上传页面看到。'),
  (r'^Stoke the fire: tell (.+) you love this game$', 'Atiça o fogo: diz a $1 que adoras este jogo', 'Aviva el fuego: dile a $1 que te encanta este juego', 'Attise le feu : dis à $1 que tu adores ce jeu', 'Fach das Feuer an: Sag $1, dass du das Spiel liebst', '添柴：告诉 $1 你喜欢这个游戏'),
  (r'^More from (.+) and friends$', 'Mais de $1 e amigos', 'Más de $1 y amigos', 'Plus de $1 et ses amis', 'Mehr von $1 und Freunden', '$1 和朋友们的更多作品'),
  (r'^More games$', 'Mais jogos', 'Más juegos', 'Plus de jeux', 'Mehr Spiele', '更多游戏'),
  (r'^(.+)’s games$', 'Jogos de $1', 'Juegos de $1', 'Les jeux de $1', 'Spiele von $1', '$1 的游戏'),
  (r'^first one added (.+)$', 'primeiro adicionado a $1', 'el primero se añadió el $1', 'le premier ajouté le $1', 'das erste hinzugefügt am $1', '第一个添加于 $1'),
  (r'^Game of the day · (.+)$', 'Jogo do dia · $1', 'Juego del día · $1', 'Jeu du jour · $1', 'Spiel des Tages · $1', '今日游戏 · $1'),
  (r'^Play every game on UsForge \((\d+)/(\d+)\)$', 'Joga todos os jogos do UsForge ($1/$2)', 'Juega todos los juegos de UsForge ($1/$2)', 'Joue à tous les jeux d’UsForge ($1/$2)', 'Spiel jedes Spiel auf UsForge ($1/$2)', '玩遍 UsForge 上的所有游戏（$1/$2）'),
  (r'^(\d+) of (\d+)$', '$1 de $2', '$1 de $2', '$1 sur $2', '$1 von $2', '$1 / $2'),
  (r'^(\d+) online now$', '$1 online agora', '$1 en línea ahora', '$1 en ligne', '$1 gerade online', '$1 人在线'),
  (r'^(\d+) playing now$', '$1 a jogar agora', '$1 jugando ahora', '$1 en train de jouer', '$1 spielen gerade', '$1 人正在玩'),
  (r'^(\d+) playing$', '$1 a jogar', '$1 jugando', '$1 en jeu', '$1 spielen', '$1 人在玩'),
  (r'^(\d+) people are browsing( the site)?\.$', '$1 pessoas estão a ver o site.', '$1 personas están viendo el sitio.', '$1 personnes regardent le site.', '$1 Leute schauen sich die Seite an.', '$1 人在浏览网站。'),
  (r'^1 person is browsing( the site)?\.$', '1 pessoa está a ver o site.', '1 persona está viendo el sitio.', '1 personne regarde le site.', '1 Person schaut sich die Seite an.', '1 人在浏览网站。'),
  (r'^(\d+) min ago$', 'há $1 min', 'hace $1 min', 'il y a $1 min', 'vor $1 Min.', '$1 分钟前'),
  (r'^(\d+) h ago$', 'há $1 h', 'hace $1 h', 'il y a $1 h', 'vor $1 Std.', '$1 小时前'),
  (r'^(\d+) d ago$', 'há $1 d', 'hace $1 d', 'il y a $1 j', 'vor $1 T.', '$1 天前'),
  (r'^\. (.+) will be pleased\.$', '. $1 vai ficar contente.', '. A $1 le va a encantar.', '. $1 va être ravi.', '. $1 wird sich freuen.', '添了柴。$1 会很高兴的。'),
  (r'^Your best is still #(\d+)\. Keep trying!$', 'O teu melhor ainda é #$1. Continua a tentar!', 'Tu mejor marca sigue siendo #$1. ¡Sigue intentándolo!', 'Ton meilleur reste #$1. Continue !', 'Dein Bestes ist noch #$1. Versuch es weiter!', '你的最佳仍是第 $1 名。继续努力！'),
  (r'^on the leaderboard!$', 'na classificação!', 'en la clasificación!', 'au classement !', 'auf der Bestenliste!', '在排行榜上！'),
  (r'^You’re$', 'Estás em', '¡Estás en el', 'Tu es', 'Du bist', '你是'),
  (r'^Theme: Auto \((light|dark) right now — light 7am–7pm\)$', 'Tema: Auto (claro das 7h às 19h)', 'Tema: Auto (claro de 7:00 a 19:00)', 'Thème : Auto (clair de 7 h à 19 h)', 'Design: Auto (hell von 7 bis 19 Uhr)', '主题：自动（早 7 点到晚 7 点为浅色）'),
  (r'^Theme: (.+)\. Click to change\.$', 'Tema: {t:$1}. Clica para mudar.', 'Tema: {t:$1}. Haz clic para cambiar.', 'Thème : {t:$1}. Clique pour changer.', 'Design: {t:$1}. Klick zum Ändern.', '主题：{t:$1}。点击切换。'),
  (r'^Theme: (.+)$', 'Tema: {t:$1}', 'Tema: {t:$1}', 'Thème : {t:$1}', 'Design: {t:$1}', '主题：{t:$1}'),
  (r'^(.+) · UsForge$', '{t:$1} · UsForge', '{t:$1} · UsForge', '{t:$1} · UsForge', '{t:$1} · UsForge', '{t:$1} · UsForge'),
]

out = Path(__file__).resolve().parent.parent / 'lang'
out.mkdir(exist_ok=True)
seen = set()
for en, *_ in ROWS:
    assert en not in seen, f'twice: {en}'
    seen.add(en)
for i, code in enumerate(CODES):
    words = {row[0]: row[1 + i] for row in ROWS}
    pats = [[p[0], p[1 + i]] for p in PATTERNS]
    js = ('// UsForge in ' + code + ' — made by scripts/langs.py (edit the table there, not this file)\n'
          'window.USF_DICT = ' + json.dumps(words, ensure_ascii=False, indent=0) + ';\n'
          'window.USF_PATTERNS = ' + json.dumps(pats, ensure_ascii=False) + ';\n')
    (out / f'{code}.js').write_text(js, encoding='utf-8')
print(f'{len(ROWS)} sentences and {len(PATTERNS)} patterns in {len(CODES)} languages')
